In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

%matplotlib inline

import warnings

warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

In [2]:
df = pd.read_csv('../data/brfss_clean.csv')

In [3]:
df=df.round(2)

In [4]:
df.columns

Index(['Unnamed: 0', 'SEXVAR', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH',
       'PERSDOC3', 'MEDCOST1', 'CHECKUP1', 'EXERANY2',
       ...
       'cholesterol_checked_within_year_was_missing',
       '_METSTAT_and_URBSTAT_was_missing', 'BPHIGH6_was_missing',
       'MARITAL_was_missing', 'RENTHOM1_was_missing', 'EMPLOY1_was_missing',
       'SMOKDAY2_was_missing', 'USENOW3_was_missing', 'ECIGNOW1_was_missing',
       '_EDUCAG_was_missing'],
      dtype='object', length=148)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377880 entries, 0 to 377879
Columns: 148 entries, Unnamed: 0 to _EDUCAG_was_missing
dtypes: bool(54), float64(93), int64(1)
memory usage: 290.5 MB

In [6]:
df = df[df.columns[1:]]
df.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPMEDS,...,ecig_never_used,white,black,asian,native,hispanic,not_graduate_high_school,graduated_high_school,attended_college,graduated_college
count,377880.000000,377880.000000,371439.000000,372553.000000,374393.000000,375303.000000,377020.000000,373877.000000,377345.000000,377549.000000,...,377373.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,376534.000000,376534.000000,376534.000000,376534.000000
mean,0.538470,1.502662,3.776157,4.125131,2.742533,0.883156,0.073198,0.778128,0.763654,0.325791,...,0.203268,0.766458,0.070504,0.025664,0.016309,0.086075,0.054301,0.246910,0.277404,0.421386
std,0.498519,1.043368,8.303671,8.133648,7.011285,0.321235,0.260461,0.415506,0.424838,0.468670,...,0.402431,0.423085,0.255995,0.158132,0.126663,0.280475,0.226610,0.431214,0.447718,0.493782
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,2.000000,2.000000,4.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,1.000000,4.000000,30.000000,30.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
df['_EDUCAG_was_missing'].describe()

count     377880
unique         2
top        False
freq      376534
Name: _EDUCAG_was_missing, dtype: object

In [8]:
df.isna().sum()

SEXVAR                     0
GENHLTH                    0
PHYSHLTH                6441
MENTHLTH                5327
POORHLTH                3487
                        ...
EMPLOY1_was_missing        0
SMOKDAY2_was_missing       0
USENOW3_was_missing        0
ECIGNOW1_was_missing       0
_EDUCAG_was_missing        0
Length: 147, dtype: int64

In [9]:
df.iloc[:, 2].isnull().sum()

6441

In [10]:
for i in range(df.shape[1]):
 # count number of rows with missing values
    n_miss = df.iloc[:, i].isnull().sum()
    perc = n_miss / df.shape[0] * 100
 #print('{:-3}Missing:{:6} ({:2.2%})'.format(i, n_miss, perc))
    print(str(perc.round(2))+"%\t"+df.columns[i])
 #print('> %d,\tMissing:\t%d\t(%.1f%%)' % (i, n_miss, perc))

0.0%	SEXVAR
0.0%	GENHLTH
1.7%	PHYSHLTH
1.41%	MENTHLTH
0.92%	POORHLTH
0.68%	PERSDOC3
0.23%	MEDCOST1
1.06%	CHECKUP1
0.14%	EXERANY2
0.09%	BPMEDS
0.65%	TOLDHI3
0.37%	CHOLMED3
0.5%	CVDINFR4
0.85%	CVDCRHD4
0.27%	CVDSTRK3
0.33%	ASTHMA3
0.4%	ASTHNOW
0.27%	CHCSCNCR
0.24%	CHCOCNCR
0.39%	CHCCOPD3
0.48%	ADDEPEV3
0.34%	CHCKDNY2
0.16%	DIABETE4
0.55%	HAVARTH5
0.22%	VETERAN3
0.1%	PREGNANT
0.29%	DEAF
0.24%	BLIND
0.57%	DECIDE
0.29%	DIFFWALK
0.12%	DIFFDRES
0.24%	DIFFALON
0.58%	SMOKE100
1.06%	ALCDAY5
1.77%	AVEDRNK3
1.71%	DRNK3GE5
2.62%	MAXDRNKS
0.73%	FLUSHOT7
8.0%	PNEUVAC4
5.07%	HIVTST7
1.69%	_METSTAT
1.69%	_URBSTAT
3.32%	_HLTHPLN
0.0%	_AGE80
2.62%	HTIN4
5.63%	WTKG3
17.81%	_INCOMG1
1.15%	FTJUDA2_
1.24%	FRUTDA2_
0.0%	GRENDA1_
0.0%	FRNCHDA_
0.0%	POTADA1_
0.0%	VEGEDA2_
0.33%	high_blood_pressure
0.33%	pregnant_high_blood_pressure
0.33%	borderline_high_blood_pressure
6.11%	cholesterol_checked_within_year
0.85%	married
0.85%	divorced
0.85%	widowed
0.85%	separated
0.85%	never_married
0.85%	unmarried_couple
0.76%	own_house
0.76%	renting
0.76%	other_arrangement_housing
0.74%	employed_for_wages
0.74%	self_employed
0.74%	out_of_work_year_plus
0.74%	out_of_work_year_less
0.74%	homemaker
0.74%	student
0.74%	retired
0.74%	unable_to_work
0.07%	smoke_every_day
0.07%	smoke_some_days
0.07%	smoke_not_at_all
0.11%	smokeless_every_day
0.11%	smokeless_some_days
0.11%	smokeless_not_at_all
0.13%	ecig_every_day
0.13%	ecig_some_days
0.13%	ecig_not_at_all
0.13%	ecig_never_used
0.0%	white
0.0%	black
0.0%	asian
0.0%	native
0.0%	hispanic
0.36%	not_graduate_high_school
0.36%	graduated_high_school
0.36%	attended_college
0.36%	graduated_college
0.0%	PHYSHLTH_was_missing
0.0%	MENTHLTH_was_missing
0.0%	POORHLTH_was_missing
0.0%	PERSDOC3_was_missing
0.0%	MEDCOST1_was_missing
0.0%	CHECKUP1_was_missing
0.0%	EXERANY2_was_missing
0.0%	BPMEDS_was_missing
0.0%	TOLDHI3_was_missing
0.0%	CHOLMED3_was_missing
0.0%	CVDINFR4_was_missing
0.0%	CVDCRHD4_was_missing
0.0%	CVDSTRK3_was_missing
0.0%	ASTHMA3_was_missing
0.0%	ASTHNOW_was_missing
0.0%	CHCSCNCR_was_missing
0.0%	CHCOCNCR_was_missing
0.0%	CHCCOPD3_was_missing
0.0%	ADDEPEV3_was_missing
0.0%	CHCKDNY2_was_missing
0.0%	DIABETE4_was_missing
0.0%	HAVARTH5_was_missing
0.0%	VETERAN3_was_missing
0.0%	PREGNANT_was_missing
0.0%	DEAF_was_missing
0.0%	BLIND_was_missing
0.0%	DECIDE_was_missing
0.0%	DIFFWALK_was_missing
0.0%	DIFFDRES_was_missing
0.0%	DIFFALON_was_missing
0.0%	SMOKE100_was_missing
0.0%	ALCDAY5_was_missing
0.0%	AVEDRNK3_was_missing
0.0%	DRNK3GE5_was_missing
0.0%	MAXDRNKS_was_missing
0.0%	FLUSHOT7_was_missing
0.0%	PNEUVAC4_was_missing
0.0%	HIVTST7_was_missing
0.0%	_HLTHPLN_was_missing
0.0%	HTIN4_was_missing
0.0%	WTKG3_was_missing
0.0%	_INCOMG1_was_missing
0.0%	FTJUDA2__was_missing
0.0%	FRUTDA2__was_missing
0.0%	cholesterol_checked_within_year_was_missing
0.0%	_METSTAT_and_URBSTAT_was_missing
0.0%	BPHIGH6_was_missing
0.0%	MARITAL_was_missing
0.0%	RENTHOM1_was_missing
0.0%	EMPLOY1_was_missing
0.0%	SMOKDAY2_was_missing
0.0%	USENOW3_was_missing
0.0%	ECIGNOW1_was_missing
0.0%	_EDUCAG_was_missing

In [11]:
f_weights = np.array([1.02, 
6.72, 
0.76, 
0.42, 
0.47, 
1.28, 
0.62, 
3.53, 
1.83, 
13.45, 
3.6, 
17.26, 
1.84, 
1.62, 
0.71, 
0.47, 
0.46, 
0.56, 
0.45, 
0.71, 
0.42, 
4.32,
1.00, #diabetes
0.91, 
0.57, 
0.25, 
0.47, 
0.78, 
0.47, 
3.1, 
0.58, 
0.72, 
0.46, 
1.84, 
1.26, 
0.62, 
1.37, 
0.66, 
4.24, 
0.42, 
0.37, 
0.39, 
0.45, 
1.72, 
0.57, 
1.59, 
0.66, 
0.93, 
0.43, 
0.43, 
0.52, 
0.58, 
0.44, 
9.16, 
1.99, 
0.32, 
5.07, 
0.37, 
0.39, 
0.49, 
0.41, 
0.71, 
0.4, 
0.58, 
0.58, 
0.4, 
0.78, 
0.54, 
0.41, 
0.41, 
0.53, 
0.85, 
1.03, 
1.33, 
0.51, 
0.45, 
0.37, 
0.44, 
0.35, 
0.4, 
0.38, 
0.39, 
0.38, 
0.38, 
1.68, 
0.99, 
0.42, 
0.85, 
0.92, 
0.55, 
0.39, 
0.39, 
0.72, 
0.36, 
0.39, 
0.35, 
0.38, 
0.21, 
0.44, 
0.33, 
0.12, 
0.35, 
0.86, 
0.31, 
0.43, 
0.29, 
0.12, 
0.35, 
0.2, 
0.26, 
0.26, 
0.17, 
0.31, 
0.26, 
0.3, 
0.17, 
0.15, #assume value
0.2, 
0.29, 
0.3, 
0.25, 
0.21, 
0.27, 
0.27, 
0.42, 
0.45, 
0.41, 
0.45, 
0.32, 
0.65, 
0.39, 
0.36, 
0.48, 
0.84, 
0.41, 
0.51, 
0.34, 
0.69, 
0.51, 
0.3, 
0.38, 
0.25, 
0.31, 
0.15,#assume value
0.13, 
0.12, 
0.23])
f_weights

array([ 1.02,  6.72,  0.76,  0.42,  0.47,  1.28,  0.62,  3.53,  1.83,
       13.45,  3.6 , 17.26,  1.84,  1.62,  0.71,  0.47,  0.46,  0.56,
        0.45,  0.71,  0.42,  4.32,  1.  ,  0.91,  0.57,  0.25,  0.47,
        0.78,  0.47,  3.1 ,  0.58,  0.72,  0.46,  1.84,  1.26,  0.62,
        1.37,  0.66,  4.24,  0.42,  0.37,  0.39,  0.45,  1.72,  0.57,
        1.59,  0.66,  0.93,  0.43,  0.43,  0.52,  0.58,  0.44,  9.16,
        1.99,  0.32,  5.07,  0.37,  0.39,  0.49,  0.41,  0.71,  0.4 ,
        0.58,  0.58,  0.4 ,  0.78,  0.54,  0.41,  0.41,  0.53,  0.85,
        1.03,  1.33,  0.51,  0.45,  0.37,  0.44,  0.35,  0.4 ,  0.38,
        0.39,  0.38,  0.38,  1.68,  0.99,  0.42,  0.85,  0.92,  0.55,
        0.39,  0.39,  0.72,  0.36,  0.39,  0.35,  0.38,  0.21,  0.44,
        0.33,  0.12,  0.35,  0.86,  0.31,  0.43,  0.29,  0.12,  0.35,
        0.2 ,  0.26,  0.26,  0.17,  0.31,  0.26,  0.3 ,  0.17,  0.  ,
        0.2 ,  0.29,  0.3 ,  0.25,  0.21,  0.27,  0.27,  0.42,  0.45,
        0.41,  0.45,  0.32,  0.65,  0.39,  0.36,  0.48,  0.84,  0.41,
        0.51,  0.34,  0.69,  0.51,  0.3 ,  0.38,  0.25,  0.31,  0.15,
        0.13,  0.12,  0.23])

In [12]:
sm = 0
length = len(f_weights)
for i in f_weights:
    sm += i
print(sm/length)

1.0009523809523804

In [13]:
data = df.copy()

In [14]:
data.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPMEDS,...,ecig_never_used,white,black,asian,native,hispanic,not_graduate_high_school,graduated_high_school,attended_college,graduated_college
count,377880.000000,377880.000000,371439.000000,372553.000000,374393.000000,375303.000000,377020.000000,373877.000000,377345.000000,377549.000000,...,377373.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,376534.000000,376534.000000,376534.000000,376534.000000
mean,0.538470,1.502662,3.776157,4.125131,2.742533,0.883156,0.073198,0.778128,0.763654,0.325791,...,0.203268,0.766458,0.070504,0.025664,0.016309,0.086075,0.054301,0.246910,0.277404,0.421386
std,0.498519,1.043368,8.303671,8.133648,7.011285,0.321235,0.260461,0.415506,0.424838,0.468670,...,0.402431,0.423085,0.255995,0.158132,0.126663,0.280475,0.226610,0.431214,0.447718,0.493782
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,2.000000,2.000000,4.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,1.000000,4.000000,30.000000,30.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
standf = scaler.fit_transform(data)
standf = pd.DataFrame(standf, columns=data.columns)
standf.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPMEDS,...,cholesterol_checked_within_year_was_missing,_METSTAT_and_URBSTAT_was_missing,BPHIGH6_was_missing,MARITAL_was_missing,RENTHOM1_was_missing,EMPLOY1_was_missing,SMOKDAY2_was_missing,USENOW3_was_missing,ECIGNOW1_was_missing,_EDUCAG_was_missing
count,377880.000000,377880.000000,371439.000000,372553.000000,374393.000000,375303.000000,377020.000000,373877.000000,377345.000000,377549.000000,...,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000
mean,0.538470,0.375666,0.125872,0.137504,0.091418,0.883156,0.073198,0.778128,0.763654,0.325791,...,0.061133,0.016900,0.003345,0.008468,0.007640,0.007391,0.000696,0.001088,0.001342,0.003562
std,0.498519,0.260842,0.276789,0.271122,0.233709,0.321235,0.260461,0.415506,0.424838,0.468670,...,0.239575,0.128895,0.057739,0.091633,0.087073,0.085654,0.026372,0.032962,0.036605,0.059576
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.250000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.250000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,0.500000,0.066667,0.133333,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [16]:
standf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377880 entries, 0 to 377879
Columns: 147 entries, SEXVAR to _EDUCAG_was_missing
dtypes: float64(147)
memory usage: 423.8 MB

In [17]:
standf.iloc[:, 0].mean()

0.5384698846194559

In [18]:
for i in range(0,len(standf.columns)):
    print(standf.iloc[:, i].mean())
    standf.iloc[:, i] *= f_weights[i]
    print("* {} = {}".format(f_weights[i], standf.iloc[:,i].mean()))

0.5384698846194559
* 1.02 = 0.5492392823118449
0.37566555520270983
* 6.72 = 2.5244725309622096
0.12587190180173147
* 0.76 = 0.0956626453693159
0.13750437297959395
* 0.42 = 0.05775183665142948
0.09141775264672863
* 0.47 = 0.042966343743962444
0.8831557434925913
* 1.28 = 1.1304393516705167
0.07319770834438491
* 0.62 = 0.04538257917351866
0.7781275660177011
* 3.53 = 2.7467903080424847
0.763653950628735
* 1.83 = 1.3974867296505846
0.32579082450225005
* 13.45 = 4.381886589555263
0.3501421003145651
* 3.6 = 1.2605115611324345
0.2657116978806705
* 17.26 = 4.586183905420374
0.051668652524521796
* 1.84 = 0.09507032064512011
0.05310008514590912
* 1.62 = 0.0860221379363728
0.0385250164512089
* 0.71 = 0.027352761680358318
0.14249377379631153
* 0.47 = 0.06697207368426641
0.09878045540292797
* 0.46 = 0.045439009485346876
0.09593003200144351
* 0.56 = 0.053720817920808364
0.09807671901528013
* 0.45 = 0.04413452355687606
0.07810984795147626
* 0.71 = 0.05545799204554814
0.20042013454941898
* 0.42 = 0.08417645651075599
0.039577037670414414
* 4.32 = 0.17097280273619025
0.14077078032230703
* 1.0 = 0.14077078032230703
0.3320932955467742
* 0.91 = 0.3022048989475644
0.12044109222837503
* 0.57 = 0.06865142257017376
0.005597336165996911
* 0.25 = 0.0013993340414992278
0.086772472730168
* 0.47 = 0.040783062183178946
0.049919621398216284
* 0.78 = 0.0389373046906087
0.1085883855857774
* 0.47 = 0.05103654122531536
0.15789990525050226
* 3.1 = 0.4894897062765572
0.03927361172564906
* 0.58 = 0.02277869480087645
0.07235081110477377
* 0.72 = 0.052092583995437126
0.40306584186878475
* 0.46 = 0.18541028725964098
0.16145112283216898
* 1.84 = 0.2970700660111909
0.015144149890875775
* 1.26 = 0.019081628862503475
0.008288061614693344
* 0.62 = 0.005138598201109872
0.022220154622748747
* 1.37 = 0.030441611833165787
0.5237752507077396
* 0.66 = 0.3456916654671081
0.40328213094005294
* 4.24 = 1.7099162351858248
0.3351759550411454
* 0.42 = 0.140773901117281
0.6932628790774548
* 0.37 = 0.2565072652586583
0.8546329146634939
* 0.39 = 0.33330683671876254
0.9474698425819732
* 0.45 = 0.42636142916188796
0.5920905937027287
* 1.72 = 1.0183958211686936
0.5262695489682335
* 0.57 = 0.29997364291189305
0.22413906728814895
* 1.59 = 0.35638111698815694
0.5619073225549893
* 0.66 = 0.370858832886293
0.004406277152662326
* 0.93 = 0.004097837751975963
0.013477305828566799
* 0.43 = 0.005795241506283725
0.00797456811151635
* 0.43 = 0.0034290642879520297
0.002552991810772059
* 0.52 = 0.001327555741601471
0.002866802886491677
* 0.58 = 0.0016627456741651716
0.014021138932459987
* 0.44 = 0.006169301130282395
0.39468848907109627
* 9.16 = 3.6153465598912424
0.00807719268432568
* 1.99 = 0.0160736134418081
0.01082269473415893
* 0.32 = 0.003463262314930858
0.7083311018972375
* 5.07 = 3.5912386866189934
0.5308663392761823
* 0.37 = 0.1964205455321875
0.12789046653144015
* 0.39 = 0.04987728194726167
0.10623465357104729
* 0.49 = 0.052054980249813185
0.01884274580975766
* 0.41 = 0.00772552578200064
0.17507473043663926
* 0.71 = 0.12430305861001383
0.041091064374933275
* 0.4 = 0.016436425749973317
0.719594765768961
* 0.58 = 0.4173649641459974
0.23299901598163167
* 0.58 = 0.13513942926934638
0.04740621824940732
* 0.4 = 0.01896248729976293
0.43531234087025145
* 0.78 = 0.3395436258787963
0.08757168336945828
* 0.54 = 0.047288709019507484
0.02588999352150301
* 0.41 = 0.010614897343816232
0.02229349457592505
* 0.41 = 0.009140332776129271
0.04078520449922285
* 0.53 = 0.02161615838458811
0.02501819577857937
* 0.85 = 0.021265466411792465
0.30546779813749875
* 1.03 = 0.3146318320816237
0.05766128924756123
* 1.33 = 0.07668951469925643
0.09215951612347961
* 0.51 = 0.047001353222974586
0.03520763101237497
* 0.45 = 0.015843433955568746
0.8726328528641454
* 0.37 = 0.32287415555973387
0.01835647430649934
* 0.44 = 0.008076848694859709
0.012811648108851322
* 0.35 = 0.004484076838097963
0.9688318775846493
* 0.4 = 0.38753275103385965
0.021668216857061846
* 0.38 = 0.008233922405683502
0.024466509262718848
* 0.39 = 0.009541938612460348
0.7505968895495968
* 0.38 = 0.2852268180288468
0.2032683843306225
* 0.38 = 0.07724198604563656
0.7664576055890759
* 1.68 = 1.2876487773896477
0.0705038636604213
* 0.99 = 0.06979882502381707
0.0256642320313327
* 0.42 = 0.010778977453159732
0.01630941039483434
* 0.85 = 0.013862998835609189
0.08607494442680216
* 0.92 = 0.079188948872658
0.05430054125258277
* 0.55 = 0.029865297688920534
0.24690997360132153
* 0.39 = 0.0962948897045154
0.2774038997806307
* 0.39 = 0.10818752091444599
0.421385585365465
* 0.72 = 0.30339762146313476
0.017045093680533502
* 0.36 = 0.006136233724992059
0.01409706785222822
* 0.39 = 0.005497856462369006
0.009227797184291309
* 0.35 = 0.0032297290145019584
0.006819625277865989
* 0.38 = 0.002591457605589076
0.002275854768709643
* 0.21 = 0.00047792950142902535
0.010593310045517095
* 0.44 = 0.004661056420027522
0.0014157933735577432
* 0.33 = 0.00046721181327405523
0.0008759394516777813
* 0.12 = 0.00010511273420133373
0.006459722663279348
* 0.35 = 0.0022609029321477713
0.0036863554567587594
* 0.86 = 0.0031702656928125333
0.004996295120143961
* 0.31 = 0.0015488514872446276
0.008545040753678417
* 0.43 = 0.003674367524081719
0.002667513496348047
* 0.29 = 0.0007735789139409336
0.0032973430718746693
* 0.12 = 0.00039568116862496024
0.0039959775590134436
* 0.35 = 0.0013985921456547055
0.0027045622949084364
* 0.2 = 0.0005409124589816873
0.0024346353339684554
* 0.26 = 0.0006330051868317985
0.003935111675664232
* 0.26 = 0.0010231290356727003
0.004789880385307505
* 0.17 = 0.0008142796655022757
0.003434952895098973
* 0.31 = 0.001064835397480682
0.0015878056525881232
* 0.26 = 0.000412829469672912
0.0055176246427437285
* 0.3 = 0.0016552873928231185
0.0021594156875198475
* 0.17 = 0.000367100666878374
0.001002963903884831
* 0.0 = 0.0
0.0028845136022017572
* 0.2 = 0.0005769027204403514
0.0024187572774425742
* 0.29 = 0.0007014396104583466
0.005663173494230973
* 0.3 = 0.0016989520482692919
0.002903038001481952
* 0.25 = 0.000725759500370488
0.001193500582195406
* 0.21 = 0.00025063512226103525
0.002447867047740023
* 0.27 = 0.0006609241028898064
0.005800783317455277
* 0.27 = 0.0015662114957129241
0.010595956388271408
* 0.42 = 0.004450301683073993
0.017653752514025615
* 0.45 = 0.007944188631311527
0.017090081507356834
* 0.41 = 0.0070069334180162994
0.02621996400973854
* 0.45 = 0.011798983804382344
0.007256271832327723
* 0.32 = 0.0023220069863448714
0.08002540489044141
* 0.65 = 0.052016513178786916
0.050682756430612895
* 0.39 = 0.019766275007939024
0.03320366253837197
* 0.36 = 0.011953318513813909
0.026222610352492855
* 0.48 = 0.01258685296919657
0.05629564941251191
* 0.84 = 0.04728834550651001
0.1781491478776331
* 0.41 = 0.07304115062982956
0.01150894463850958
* 0.51 = 0.005869561765639884
0.012374298719170108
* 0.34 = 0.0042072615645178365
0.061133163967397056
* 0.69 = 0.04218188313750396
0.016899544829046258
* 0.51 = 0.008618767862813589
0.003344977241452313
* 0.3 = 0.0010034931724356936
0.008468296813803323
* 0.38 = 0.003217952789245263
0.007639991531703186
* 0.25 = 0.0019099978829257966
0.007391235312797713
* 0.31 = 0.0022912829469672906
0.0006959881443844607
* 0.15 = 0.00010439822165766909
0.0010876468720228643
* 0.13 = 0.0001413940933629724
0.0013416957764369642
* 0.12 = 0.00016100349317243573
0.003561977347306023
* 0.23 = 0.0008192547898803855

In [19]:
standf.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPMEDS,...,cholesterol_checked_within_year_was_missing,_METSTAT_and_URBSTAT_was_missing,BPHIGH6_was_missing,MARITAL_was_missing,RENTHOM1_was_missing,EMPLOY1_was_missing,SMOKDAY2_was_missing,USENOW3_was_missing,ECIGNOW1_was_missing,_EDUCAG_was_missing
count,377880.000000,377880.000000,371439.000000,372553.000000,374393.000000,375303.000000,377020.000000,373877.000000,377345.000000,377549.000000,...,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000
mean,0.549239,2.524473,0.095663,0.057752,0.042966,1.130439,0.045383,2.746790,1.397487,4.381887,...,0.042182,0.008619,0.001003,0.003218,0.001910,0.002291,0.000104,0.000141,0.000161,0.000819
std,0.508489,1.752858,0.210360,0.113871,0.109843,0.411181,0.161486,1.466737,0.777453,6.303614,...,0.165307,0.065737,0.017322,0.034821,0.021768,0.026553,0.003956,0.004285,0.004393,0.013702
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.680000,0.000000,0.000000,0.000000,1.280000,0.000000,3.530000,1.830000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.020000,1.680000,0.000000,0.000000,0.000000,1.280000,0.000000,3.530000,1.830000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.020000,3.360000,0.050667,0.056000,0.000000,1.280000,0.000000,3.530000,1.830000,13.450000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.020000,6.720000,0.760000,0.420000,0.470000,1.280000,0.620000,3.530000,1.830000,13.450000,...,0.690000,0.510000,0.300000,0.380000,0.250000,0.310000,0.150000,0.130000,0.120000,0.230000

In [20]:
# imputation
#from sklearn.impute import SimpleImputer

#df_imputer = SimpleImputer()
#imputed_df = pd.DataFrame(df_imputer.fit_transform(df_mis))

#iterative imputer
#imputed_df.columns = df_mis.columns
#from fancyimpute import IterativeImputer

#imputed_df = IterativeImputer().fit_transform(df_mis)

#KNN
#from fancyimpute import KNN

#imputed_df = KNN(k=3).fit_transform(df_mis)

from sklearn.impute import KNNImputer

imputed_df = KNNImputer(n_neighbors=1).fit_transform(standf)

imputed_df.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [21]:
imputed_df

array([[1.02      , 6.72      , 0.50666667, ..., 0.        , 0.        ,
        0.        ],
       [1.02      , 3.36      , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.02      , 1.68      , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 1.68      , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.68      , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.02      , 0.        , 0.05066667, ..., 0.        , 0.        ,
        0.        ]])

In [23]:
impdf = imputed_df

In [25]:
imputed_df = pd.DataFrame(imputed_df, columns=data.columns)

In [26]:
for i in range(0,len(standf.columns)):
    print(imputed_df.iloc[:, i].mean())
    imputed_df.iloc[:, i] /= f_weights[i]
    print("/ {} = {}".format(f_weights[i], imputed_df.iloc[:,i].mean()))

0.5492392823118449
/ 1.02 = 0.5384698846194559
2.5244725309622096
/ 6.72 = 0.37566555520270983
0.09694364348470413
/ 0.76 = 0.12755742563776856
0.057803424367524094
/ 0.42 = 0.13762720087505736
0.04347060530679933
/ 0.47 = 0.09249064958893478
1.12932528845136
/ 1.28 = 0.8822853816026252
0.04543188313750396
/ 0.62 = 0.07327723086694189
2.7396828093574683
/ 3.53 = 0.776114110299566
1.3972661162273732
/ 1.83 = 0.7635333968455594
4.387516142690802
/ 13.45 = 0.3262093786387213
1.261438551921245
/ 3.6 = 0.35039959775590135
4.595404202392294
/ 17.26 = 0.2662458981687308
0.09579803112099083
/ 1.84 = 0.05206414734836456
0.08816370276278185
/ 1.62 = 0.05442203874245792
0.027409442150947386
/ 0.71 = 0.038604848099925905
0.06695522388059702
/ 0.47 = 0.14245792315020642
0.045646977876574575
/ 0.46 = 0.09923256060124908
0.05378151794220389
/ 0.56 = 0.09603842489679264
0.044183073991743406
/ 0.45 = 0.09818460887054091
0.05561553932465333
/ 0.71 = 0.07833174552768074
0.08420562083201018
/ 0.42 = 0.200489573409548
0.1717688154969832
/ 4.32 = 0.03976129988356092
0.1407960199004975
/ 1.0 = 0.1407960199004975
0.30239173811792097
/ 0.91 = 0.33229861331639676
0.06870832010161955
/ 0.57 = 0.12054091245898169
0.0014038848311633324
/ 0.25 = 0.0056155393246533295
0.04082587064676616
/ 0.47 = 0.0868635545675876
0.03898761511590982
/ 0.78 = 0.04998412194347412
0.05112562189054726
/ 0.47 = 0.10877791891605801
0.49039853921879967
/ 3.1 = 0.15819307716735473
0.022874298719170103
/ 0.58 = 0.03943844606753467
0.05225658939345824
/ 0.72 = 0.07257859637980311
0.18519784058431246
/ 0.46 = 0.40260400127024454
0.29718911823859423
/ 1.84 = 0.16151582512967078
0.019158011733048087
/ 1.26 = 0.015204771216704828
0.005190111870657908
/ 0.62 = 0.008371148178480498
0.03077654246962276
/ 1.37 = 0.022464629539870634
0.3455795490631946
/ 0.66 = 0.5236053773684768
1.6574688260823545
/ 4.24 = 0.3909124589816873
0.13950651000317563
/ 0.42 = 0.33215835715041814
0.2571494125119086
/ 0.37 = 0.6949984121943474
0.33379017148301043
/ 0.39 = 0.8558722345718217
0.42618886948237533
/ 0.45 = 0.9470863766275008
1.0183958211686936
/ 1.72 = 0.5920905937027287
0.2996851394846897
/ 0.57 = 0.5257634026047188
0.35548431121268026
/ 1.59 = 0.223575038498541
0.3703409018736107
/ 0.66 = 0.5611225785963799
0.004092209864603482
/ 0.93 = 0.004400225660863959
0.005782708577251289
/ 0.43 = 0.013448159481979742
0.0034290642879520297
/ 0.43 = 0.00797456811151635
0.001327555741601471
/ 0.52 = 0.002552991810772059
0.0016627456741651716
/ 0.58 = 0.002866802886491677
0.006169301130282395
/ 0.44 = 0.014021138932459987
3.606671218376203
/ 9.16 = 0.39374139938604846
0.016088308457711444
/ 1.99 = 0.00808457711442786
0.003473695353022123
/ 0.32 = 0.010855297978194135
3.528297634169577
/ 5.07 = 0.6959166931300942
0.1965421827035037
/ 0.37 = 0.531195088387848
0.04978620196887901
/ 0.39 = 0.1276569281253308
0.05195001058537103
/ 0.49 = 0.1060204297660633
0.00772628876892135
/ 0.41 = 0.01884460675346671
0.12438715994495611
/ 0.71 = 0.1751931830210649
0.016435905578490523
/ 0.4 = 0.041089763946226314
0.4172537313432835
/ 0.58 = 0.7194029850746269
0.1351353339684556
/ 0.58 = 0.2329919551180269
0.0190420239229385
/ 0.4 = 0.04760505980734625
0.34007446808510644
/ 0.78 = 0.4359929078014184
0.047315020641473485
/ 0.54 = 0.08762040859532126
0.01061673017889277
/ 0.41 = 0.025894463850957977
0.009144384460675347
/ 0.41 = 0.022303376733354505
0.02164152641050069
/ 0.53 = 0.0408330686990579
0.02135797078437599
/ 0.85 = 0.02512702445220705
0.31380001587805645
/ 1.03 = 0.3046602095903461
0.07656615856885783
/ 1.33 = 0.05756854027733672
0.04702262623054938
/ 0.51 = 0.092201227903038
0.015850269926960946
/ 0.45 = 0.0352228220599132
0.3228531015137081
/ 0.37 = 0.8725759500370488
0.008076214671324229
/ 0.44 = 0.018355033343918706
0.004485683285699163
/ 0.35 = 0.012816237959140468
0.3875314914787764
/ 0.4 = 0.9688287286969408
0.00822991425849476
/ 0.38 = 0.021657669101302
0.009540489044140997
/ 0.39 = 0.024462792420874353
0.2852232454747538
/ 0.38 = 0.7505874880914576
0.07725097914681911
/ 0.38 = 0.20329205038636605
1.2876487773896477
/ 1.68 = 0.7664576055890759
0.06979882502381707
/ 0.99 = 0.0705038636604213
0.010778977453159732
/ 0.42 = 0.0256642320313327
0.013862998835609189
/ 0.85 = 0.01630941039483434
0.079188948872658
/ 0.92 = 0.08607494442680216
0.029889912141420553
/ 0.55 = 0.05434529480258283
0.09629969831692602
/ 0.39 = 0.24692230337673335
0.10817783423308988
/ 0.39 = 0.2773790621361279
0.30337440457288023
/ 0.72 = 0.42135333968455596
0.006136233724992059
/ 0.36 = 0.017045093680533502
0.005497856462369006
/ 0.39 = 0.01409706785222822
0.0032297290145019584
/ 0.35 = 0.009227797184291309
0.002591457605589076
/ 0.38 = 0.006819625277865989
0.00047792950142902535
/ 0.21 = 0.002275854768709643
0.004661056420027522
/ 0.44 = 0.010593310045517095
0.00046721181327405523
/ 0.33 = 0.0014157933735577432
0.00010511273420133373
/ 0.12 = 0.0008759394516777813
0.0022609029321477713
/ 0.35 = 0.006459722663279348
0.0031702656928125333
/ 0.86 = 0.0036863554567587594
0.0015488514872446276
/ 0.31 = 0.004996295120143961
0.003674367524081719
/ 0.43 = 0.008545040753678417
0.0007735789139409336
/ 0.29 = 0.002667513496348047
0.00039568116862496024
/ 0.12 = 0.0032973430718746693
0.0013985921456547055
/ 0.35 = 0.0039959775590134436
0.0005409124589816873
/ 0.2 = 0.0027045622949084364
0.0006330051868317985
/ 0.26 = 0.0024346353339684554
0.0010231290356727003
/ 0.26 = 0.003935111675664232
0.0008142796655022757
/ 0.17 = 0.004789880385307505
0.001064835397480682
/ 0.31 = 0.003434952895098973
0.000412829469672912
/ 0.26 = 0.0015878056525881232
0.0016552873928231185
/ 0.3 = 0.0055176246427437285
0.000367100666878374
/ 0.17 = 0.0021594156875198475
0.0
/ 0.0 = nan
0.0005769027204403514
/ 0.2 = 0.0028845136022017572
0.0007014396104583466
/ 0.29 = 0.0024187572774425742
0.0016989520482692919
/ 0.3 = 0.005663173494230973
0.000725759500370488
/ 0.25 = 0.002903038001481952
0.00025063512226103525
/ 0.21 = 0.001193500582195406
0.0006609241028898064
/ 0.27 = 0.002447867047740023
0.0015662114957129241
/ 0.27 = 0.005800783317455277
0.004450301683073993
/ 0.42 = 0.010595956388271408
0.007944188631311527
/ 0.45 = 0.017653752514025615
0.0070069334180162994
/ 0.41 = 0.017090081507356834
0.011798983804382344
/ 0.45 = 0.02621996400973854
0.0023220069863448714
/ 0.32 = 0.007256271832327723
0.052016513178786916
/ 0.65 = 0.08002540489044141
0.019766275007939024
/ 0.39 = 0.050682756430612895
0.011953318513813909
/ 0.36 = 0.03320366253837197
0.01258685296919657
/ 0.48 = 0.026222610352492855
0.04728834550651001
/ 0.84 = 0.05629564941251191
0.07304115062982956
/ 0.41 = 0.1781491478776331
0.005869561765639884
/ 0.51 = 0.01150894463850958
0.0042072615645178365
/ 0.34 = 0.012374298719170108
0.04218188313750396
/ 0.69 = 0.061133163967397056
0.008618767862813589
/ 0.51 = 0.016899544829046258
0.0010034931724356936
/ 0.3 = 0.003344977241452313
0.003217952789245263
/ 0.38 = 0.008468296813803323
0.0019099978829257966
/ 0.25 = 0.007639991531703186
0.0022912829469672906
/ 0.31 = 0.007391235312797713
0.00010439822165766909
/ 0.15 = 0.0006959881443844607
0.0001413940933629724
/ 0.13 = 0.0010876468720228643
0.00016100349317243573
/ 0.12 = 0.0013416957764369642
0.0008192547898803855
/ 0.23 = 0.003561977347306023

In [27]:
#invert
imputed_df = pd.DataFrame(scaler.inverse_transform(imputed_df), columns=data.columns)
imputed_df.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPMEDS,...,cholesterol_checked_within_year_was_missing,_METSTAT_and_URBSTAT_was_missing,BPHIGH6_was_missing,MARITAL_was_missing,RENTHOM1_was_missing,EMPLOY1_was_missing,SMOKDAY2_was_missing,USENOW3_was_missing,ECIGNOW1_was_missing,_EDUCAG_was_missing
count,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,...,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000
mean,0.538470,1.502662,3.826723,4.128816,2.774719,0.882285,0.073277,0.776114,0.763533,0.326209,...,0.061133,0.016900,0.003345,0.008468,0.007640,0.007391,0.000696,0.001088,0.001342,0.003562
std,0.498519,1.043368,8.357974,8.138850,7.058854,0.322270,0.260591,0.416847,0.424912,0.468826,...,0.239575,0.128895,0.057739,0.091633,0.087073,0.085654,0.026372,0.032962,0.036605,0.059576
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,2.000000,2.000000,4.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,4.000000,30.000000,30.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

print("No. of columns containing null values")
print(len(imputed_df.columns[imputed_df.isna().any()]))

print("No. of columns not containing null values")
print(len(imputed_df.columns[imputed_df.notna().all()]))

print("Total no. of columns in the dataframe")
print(len(imputed_df.columns))

#df = df.dropna(axis=1)
#df.shape

In [28]:
imputed_df=imputed_df.round(2)

In [33]:
imputed_df.to_csv('../data/brfss_imputed_2.csv')

In [30]:
df['PREGNANT_was_missing'].describe()

count     377880
unique         2
top        False
freq      377501
Name: PREGNANT_was_missing, dtype: object

In [32]:
imputed_df['PREGNANT_was_missing'] = df['PREGNANT_was_missing']
imputed_df['PREGNANT_was_missing'].describe()

count     377880
unique         2
top        False
freq      377501
Name: PREGNANT_was_missing, dtype: object

In [4]:
imputed_df

array([[0.00000e+00, 1.00000e+00, 4.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [1.00000e+00, 1.00000e+00, 2.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [2.00000e+00, 1.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [3.78561e+05, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [3.78562e+05, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [3.78563e+05, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00]])

In [7]:
imdf = pd.DataFrame(imputed_df, columns=df.columns)
imdf.describe()

,Unnamed: 0,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,...,smokeless_some_days_was_missing,smokeless_not_at_all_was_missing,ecig_every_day_was_missing,ecig_some_days_was_missing,ecig_not_at_all_was_missing,ecig_never_used_was_missing,not_graduate_high_school_was_missing,graduated_high_school_was_missing,attended_college_was_missing,graduated_college_was_missing
count,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,...,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000
mean,189275.236231,0.538470,1.502662,3.783661,4.120906,2.758177,0.883024,0.073253,0.777720,0.763602,...,0.001088,0.001088,0.001342,0.001342,0.001342,0.001342,0.003562,0.003562,0.003562,0.003562
std,109278.606089,0.498519,1.043368,8.312136,8.131098,7.034716,0.321392,0.260552,0.415779,0.424870,...,0.032962,0.032962,0.036605,0.036605,0.036605,0.036605,0.059576,0.059576,0.059576,0.059576
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,94640.750000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,189273.500000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,283908.250000,1.000000,2.000000,2.000000,4.000000,0.000000,1.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,378563.000000,1.000000,4.000000,30.000000,30.000000,30.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
df.columns

Index(['Unnamed: 0', 'SEXVAR', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH',
       'PERSDOC3', 'MEDCOST1', 'CHECKUP1', 'EXERANY2',
       ...
       'smokeless_some_days_was_missing', 'smokeless_not_at_all_was_missing',
       'ecig_every_day_was_missing', 'ecig_some_days_was_missing',
       'ecig_not_at_all_was_missing', 'ecig_never_used_was_missing',
       'not_graduate_high_school_was_missing',
       'graduated_high_school_was_missing', 'attended_college_was_missing',
       'graduated_college_was_missing'],
      dtype='object', length=178)

In [8]:
df2 = imdf[imdf.columns[1:]]
df2.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPMEDS,...,smokeless_some_days_was_missing,smokeless_not_at_all_was_missing,ecig_every_day_was_missing,ecig_some_days_was_missing,ecig_not_at_all_was_missing,ecig_never_used_was_missing,not_graduate_high_school_was_missing,graduated_high_school_was_missing,attended_college_was_missing,graduated_college_was_missing
count,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,...,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000
mean,0.538470,1.502662,3.783661,4.120906,2.758177,0.883024,0.073253,0.777720,0.763602,0.325876,...,0.001088,0.001088,0.001342,0.001342,0.001342,0.001342,0.003562,0.003562,0.003562,0.003562
std,0.498519,1.043368,8.312136,8.131098,7.034716,0.321392,0.260552,0.415779,0.424870,0.468702,...,0.032962,0.032962,0.036605,0.036605,0.036605,0.036605,0.059576,0.059576,0.059576,0.059576
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,2.000000,2.000000,4.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,4.000000,30.000000,30.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df2.to_csv('./data/brfss_imputed.csv')