In [1]:
import numpy as np
import pandas as pd

In [110]:
p = pd.read_csv('./input_test.csv')

In [111]:
p = p[p.columns[1:]]

In [112]:
p.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPHIGH6,...,FRUTDA2_,FRUTDA2_2,GRENDA1_,GRENDA1_2,FRNCHDA_,FRNCHDA_2,POTADA1_,POTADA1_2,VEGEDA2_,VEGEDA2_2
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,0.0,1.0,15.0,1.0,3.0,0.0,1.0,0.0,1.0,0.0,...,3.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,4.0,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.0,1.0,15.0,1.0,3.0,0.0,1.0,0.0,1.0,0.0,...,3.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,4.0,0.0
25%,0.0,1.0,15.0,1.0,3.0,0.0,1.0,0.0,1.0,0.0,...,3.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,4.0,0.0
50%,0.0,1.0,15.0,1.0,3.0,0.0,1.0,0.0,1.0,0.0,...,3.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,4.0,0.0
75%,0.0,1.0,15.0,1.0,3.0,0.0,1.0,0.0,1.0,0.0,...,3.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,4.0,0.0
max,0.0,1.0,15.0,1.0,3.0,0.0,1.0,0.0,1.0,0.0,...,3.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,4.0,0.0

In [45]:
#df = pd.read_csv('../data/brfss_imputed.csv')
df = pd.read_csv('./X_test.csv')

In [46]:
df = df[df.columns[1:]]

In [47]:
df.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPMEDS,...,cholesterol_checked_within_year_was_missing,_METSTAT_and_URBSTAT_was_missing,BPHIGH6_was_missing,MARITAL_was_missing,RENTHOM1_was_missing,EMPLOY1_was_missing,SMOKDAY2_was_missing,USENOW3_was_missing,ECIGNOW1_was_missing,_EDUCAG_was_missing
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [94]:
for i in range(0, len(df.columns)):
    print("["+str(i)+"]\tdf: "+df.columns[i])

[0]	df: SEXVAR
[1]	df: GENHLTH
[2]	df: PHYSHLTH
[3]	df: MENTHLTH
[4]	df: POORHLTH
[5]	df: PERSDOC3
[6]	df: MEDCOST1
[7]	df: CHECKUP1
[8]	df: EXERANY2
[9]	df: BPMEDS
[10]	df: TOLDHI3
[11]	df: CHOLMED3
[12]	df: CVDINFR4
[13]	df: CVDCRHD4
[14]	df: CVDSTRK3
[15]	df: ASTHMA3
[16]	df: ASTHNOW
[17]	df: CHCSCNCR
[18]	df: CHCOCNCR
[19]	df: CHCCOPD3
[20]	df: ADDEPEV3
[21]	df: CHCKDNY2
[22]	df: HAVARTH5
[23]	df: VETERAN3
[24]	df: PREGNANT
[25]	df: DEAF
[26]	df: BLIND
[27]	df: DECIDE
[28]	df: DIFFWALK
[29]	df: DIFFDRES
[30]	df: DIFFALON
[31]	df: SMOKE100
[32]	df: ALCDAY5
[33]	df: AVEDRNK3
[34]	df: DRNK3GE5
[35]	df: MAXDRNKS
[36]	df: FLUSHOT7
[37]	df: PNEUVAC4
[38]	df: HIVTST7
[39]	df: _METSTAT
[40]	df: _URBSTAT
[41]	df: _HLTHPLN
[42]	df: _AGE80
[43]	df: HTIN4
[44]	df: WTKG3
[45]	df: _INCOMG1
[46]	df: FTJUDA2_
[47]	df: FRUTDA2_
[48]	df: GRENDA1_
[49]	df: FRNCHDA_
[50]	df: POTADA1_
[51]	df: VEGEDA2_
[52]	df: high_blood_pressure
[53]	df: pregnant_high_blood_pressure
[54]	df: borderline_high_blood_pressure
[55]	df: cholesterol_checked_within_year
[56]	df: married
[57]	df: divorced
[58]	df: widowed
[59]	df: separated
[60]	df: never_married
[61]	df: unmarried_couple
[62]	df: own_house
[63]	df: renting
[64]	df: other_arrangement_housing
[65]	df: employed_for_wages
[66]	df: self_employed
[67]	df: out_of_work_year_plus
[68]	df: out_of_work_year_less
[69]	df: homemaker
[70]	df: student
[71]	df: retired
[72]	df: unable_to_work
[73]	df: smoke_every_day
[74]	df: smoke_some_days
[75]	df: smoke_not_at_all
[76]	df: smokeless_every_day
[77]	df: smokeless_some_days
[78]	df: smokeless_not_at_all
[79]	df: ecig_every_day
[80]	df: ecig_some_days
[81]	df: ecig_not_at_all
[82]	df: ecig_never_used
[83]	df: white
[84]	df: black
[85]	df: asian
[86]	df: native
[87]	df: hispanic
[88]	df: not_graduate_high_school
[89]	df: graduated_high_school
[90]	df: attended_college
[91]	df: graduated_college
[92]	df: PHYSHLTH_was_missing
[93]	df: MENTHLTH_was_missing
[94]	df: POORHLTH_was_missing
[95]	df: PERSDOC3_was_missing
[96]	df: MEDCOST1_was_missing
[97]	df: CHECKUP1_was_missing
[98]	df: EXERANY2_was_missing
[99]	df: BPMEDS_was_missing
[100]	df: TOLDHI3_was_missing
[101]	df: CHOLMED3_was_missing
[102]	df: CVDINFR4_was_missing
[103]	df: CVDCRHD4_was_missing
[104]	df: CVDSTRK3_was_missing
[105]	df: ASTHMA3_was_missing
[106]	df: ASTHNOW_was_missing
[107]	df: CHCSCNCR_was_missing
[108]	df: CHCOCNCR_was_missing
[109]	df: CHCCOPD3_was_missing
[110]	df: ADDEPEV3_was_missing
[111]	df: CHCKDNY2_was_missing
[112]	df: DIABETE4_was_missing
[113]	df: HAVARTH5_was_missing
[114]	df: VETERAN3_was_missing
[115]	df: PREGNANT_was_missing
[116]	df: DEAF_was_missing
[117]	df: BLIND_was_missing
[118]	df: DECIDE_was_missing
[119]	df: DIFFWALK_was_missing
[120]	df: DIFFDRES_was_missing
[121]	df: DIFFALON_was_missing
[122]	df: SMOKE100_was_missing
[123]	df: ALCDAY5_was_missing
[124]	df: AVEDRNK3_was_missing
[125]	df: DRNK3GE5_was_missing
[126]	df: MAXDRNKS_was_missing
[127]	df: FLUSHOT7_was_missing
[128]	df: PNEUVAC4_was_missing
[129]	df: HIVTST7_was_missing
[130]	df: _HLTHPLN_was_missing
[131]	df: HTIN4_was_missing
[132]	df: WTKG3_was_missing
[133]	df: _INCOMG1_was_missing
[134]	df: FTJUDA2__was_missing
[135]	df: FRUTDA2__was_missing
[136]	df: cholesterol_checked_within_year_was_missing
[137]	df: _METSTAT_and_URBSTAT_was_missing
[138]	df: BPHIGH6_was_missing
[139]	df: MARITAL_was_missing
[140]	df: RENTHOM1_was_missing
[141]	df: EMPLOY1_was_missing
[142]	df: SMOKDAY2_was_missing
[143]	df: USENOW3_was_missing
[144]	df: ECIGNOW1_was_missing
[145]	df: _EDUCAG_was_missing

In [93]:
for i in range(0, len(df.columns)):
    print("["+str(i)+"]\tdf: "+df.columns[i]+"\tp: "+p.columns[i])

[0]	df: SEXVAR	p: SEXVAR
[1]	df: GENHLTH	p: GENHLTH
[2]	df: PHYSHLTH	p: PHYSHLTH
[3]	df: MENTHLTH	p: MENTHLTH
[4]	df: POORHLTH	p: POORHLTH
[5]	df: PERSDOC3	p: PERSDOC3
[6]	df: MEDCOST1	p: MEDCOST1
[7]	df: CHECKUP1	p: CHECKUP1
[8]	df: EXERANY2	p: EXERANY2
[9]	df: BPMEDS	p: BPMEDS
[10]	df: TOLDHI3	p: TOLDHI3
[11]	df: CHOLMED3	p: CHOLMED3
[12]	df: CVDINFR4	p: CVDINFR4
[13]	df: CVDCRHD4	p: CVDCRHD4
[14]	df: CVDSTRK3	p: CVDSTRK3
[15]	df: ASTHMA3	p: ASTHMA3
[16]	df: ASTHNOW	p: ASTHNOW
[17]	df: CHCSCNCR	p: CHCSCNCR
[18]	df: CHCOCNCR	p: CHCOCNCR
[19]	df: CHCCOPD3	p: CHCCOPD3
[20]	df: ADDEPEV3	p: ADDEPEV3
[21]	df: CHCKDNY2	p: CHCKDNY2
[22]	df: HAVARTH5	p: HAVARTH5
[23]	df: VETERAN3	p: VETERAN3
[24]	df: PREGNANT	p: PREGNANT
[25]	df: DEAF	p: DEAF
[26]	df: BLIND	p: BLIND
[27]	df: DECIDE	p: DECIDE
[28]	df: DIFFWALK	p: DIFFWALK
[29]	df: DIFFDRES	p: DIFFDRES
[30]	df: DIFFALON	p: DIFFALON
[31]	df: SMOKE100	p: SMOKE100
[32]	df: ALCDAY5	p: ALCDAY5
[33]	df: AVEDRNK3	p: AVEDRNK3
[34]	df: DRNK3GE5	p: DRNK3GE5
[35]	df: MAXDRNKS	p: MAXDRNKS
[36]	df: FLUSHOT7	p: FLUSHOT7
[37]	df: PNEUVAC4	p: PNEUVAC4
[38]	df: HIVTST7	p: HIVTST7
[39]	df: _METSTAT	p: _METSTAT
[40]	df: _URBSTAT	p: _URBSTAT
[41]	df: _HLTHPLN	p: _HLTHPLN
[42]	df: _AGE80	p: _AGE80
[43]	df: HTIN4	p: HTIN4
[44]	df: WTKG3	p: WTKG3
[45]	df: _INCOMG1	p: _INCOMG1
[46]	df: FTJUDA2_	p: FTJUDA2_
[47]	df: FRUTDA2_	p: FRUTDA2_
[48]	df: GRENDA1_	p: GRENDA1_
[49]	df: FRNCHDA_	p: FRNCHDA_
[50]	df: POTADA1_	p: POTADA1_
[51]	df: VEGEDA2_	p: VEGEDA2_
[52]	df: high_blood_pressure	p: high_blood_pressure
[53]	df: pregnant_high_blood_pressure	p: pregnant_high_blood_pressure
[54]	df: borderline_high_blood_pressure	p: borderline_high_blood_pressure
[55]	df: cholesterol_checked_within_year	p: cholesterol_checked_within_year
[56]	df: married	p: married
[57]	df: divorced	p: divorced
[58]	df: widowed	p: widowed
[59]	df: separated	p: separated
[60]	df: never_married	p: never_married
[61]	df: unmarried_couple	p: unmarried_couple
[62]	df: own_house	p: own_house
[63]	df: renting	p: renting
[64]	df: other_arrangement_housing	p: other_arrangement_housing
[65]	df: employed_for_wages	p: employed_for_wages
[66]	df: self_employed	p: self_employed
[67]	df: out_of_work_year_plus	p: out_of_work_year_plus
[68]	df: out_of_work_year_less	p: out_of_work_year_less
[69]	df: homemaker	p: homemaker
[70]	df: student	p: student
[71]	df: retired	p: retired
[72]	df: unable_to_work	p: unable_to_work
[73]	df: smoke_every_day	p: smoke_every_day
[74]	df: smoke_some_days	p: smoke_some_days
[75]	df: smoke_not_at_all	p: smoke_not_at_all
[76]	df: smokeless_every_day	p: smokeless_every_day
[77]	df: smokeless_some_days	p: smokeless_some_days
[78]	df: smokeless_not_at_all	p: smokeless_not_at_all
[79]	df: ecig_every_day	p: ecig_every_day
[80]	df: ecig_some_days	p: ecig_some_days
[81]	df: ecig_not_at_all	p: ecig_not_at_all
[82]	df: ecig_never_used	p: ecig_never_used
[83]	df: white	p: white
[84]	df: black	p: black
[85]	df: asian	p: asian
[86]	df: native	p: native
[87]	df: hispanic	p: hispanic
[88]	df: not_graduate_high_school	p: not_graduate_high_school
[89]	df: graduated_high_school	p: graduated_high_school
[90]	df: attended_college	p: attended_college
[91]	df: graduated_college	p: graduated_college

IndexError: index 92 is out of bounds for axis 0 with size 92

In [106]:
for i in range(0, len(df.columns)):
    if df.columns[i] != p.columns[i]:
        print("["+str(i)+"]\tdf: "+df.columns[i]+"\tp: "+p.columns[i])

# BPHIGH6

In [113]:
p['high_blood_pressure'] = p['BPHIGH6']
p['high_blood_pressure'].replace([0,1,2],0, inplace=True)
p['high_blood_pressure'].replace(3,1, inplace=True)
p['pregnant_high_blood_pressure'] = p['BPHIGH6']
p['pregnant_high_blood_pressure'].replace([0,1,3],0, inplace=True)
p['pregnant_high_blood_pressure'].replace(2,1, inplace=True)
p['borderline_high_blood_pressure'] = p['BPHIGH6']
p['borderline_high_blood_pressure'].replace([0,2,3],0, inplace=True)
p = p.drop(['BPHIGH6'], axis=1)

# CHOLCHK3

In [114]:
# cholesterol checked within last year
p['cholesterol_checked_within_year'] = p['CHOLCHK3']
p = p.drop(['CHOLCHK3'], axis=1)

# MARITAL

In [115]:
# married
p['married'] = p['MARITAL']
p['married'].replace([1,2,3,4,5],2, inplace=True)
p['married'].replace(0,1, inplace=True)
p['married'].replace(2,0, inplace=True)
# divorced
p['divorced'] = p['MARITAL']
p['divorced'].replace([0,2,3,4,5],0, inplace=True)
# widowed
p['widowed'] = p['MARITAL']
p['widowed'].replace([1,3,4,5],0, inplace=True)
p['widowed'].replace(2,1, inplace=True)
# separated
p['separated'] = p['MARITAL']
p['separated'].replace([1,2,4,5],0, inplace=True)
p['separated'].replace(3,1, inplace=True)
# never_married
p['never_married'] = p['MARITAL']
p['never_married'].replace([1,2,3,5],0, inplace=True)
p['never_married'].replace(4,1, inplace=True)
# unmarried_couple
p['unmarried_couple'] = p['MARITAL']
p['unmarried_couple'].replace([1,2,3,4],0, inplace=True)
p['unmarried_couple'].replace(5,1, inplace=True)
p = p.drop(['MARITAL'], axis=1)

# RENTHOM1

In [116]:
# own
p['own_house'] = p['RENTHOM1']
p['own_house'].replace([1,2],2, inplace=True)
p['own_house'].replace(0,1, inplace=True)
p['own_house'].replace(2,0, inplace=True)
# renting
p['renting'] = p['RENTHOM1']
p['renting'].replace([0,2],0, inplace=True)
# other_arrangement_housing
p['other_arrangement_housing'] = p['RENTHOM1']
p['other_arrangement_housing'].replace([0,1],0, inplace=True)
p['other_arrangement_housing'].replace(2,1, inplace=True)
p = p.drop(['RENTHOM1'], axis=1)

# EMPLOY1

In [117]:
# employed for wages
p['employed_for_wages'] = p['EMPLOY1']
p['employed_for_wages'].replace(0,10, inplace=True)
p['employed_for_wages'].replace([1,2,3,4,5,6,7],0, inplace=True)
p['employed_for_wages'].replace(10,1, inplace=True)
# self_employed
p['self_employed'] = p['EMPLOY1']
p['self_employed'].replace([2,3,4,5,6,7],0, inplace=True)
# out_of_work_year_plus
p['out_of_work_year_plus'] = p['EMPLOY1']
p['out_of_work_year_plus'].replace([1,3,4,5,6,7],0, inplace=True)
p['out_of_work_year_plus'].replace(2,1, inplace=True)
# out_of_work_year_less
p['out_of_work_year_less'] = p['EMPLOY1']
p['out_of_work_year_less'].replace([1,2,4,5,6,7],0, inplace=True)
p['out_of_work_year_less'].replace(3,1, inplace=True)
# homemaker
p['homemaker'] = p['EMPLOY1']
p['homemaker'].replace([1,2,3,5,6,7],0, inplace=True)
p['homemaker'].replace(4,1, inplace=True)
# student
p['student'] = p['EMPLOY1']
p['student'].replace([1,2,3,4,6,7],0, inplace=True)
p['student'].replace(5,1, inplace=True)
# retired
p['retired'] = p['EMPLOY1']
p['retired'].replace([1,2,3,4,5,7],0, inplace=True)
p['retired'].replace(6,1, inplace=True)
# unable_to_work
p['unable_to_work'] = p['EMPLOY1']
p['unable_to_work'].replace([1,2,3,4,5,6],0, inplace=True)
p['unable_to_work'].replace(7,1, inplace=True)
p = p.drop(['EMPLOY1'], axis=1)

# SMOKDAY2

In [118]:
# smoke every day
p['smoke_every_day'] = p['SMOKDAY2']
p['smoke_every_day'].replace(0,3,inplace=True)
p['smoke_every_day'].replace([1,2],0,inplace=True)
p['smoke_every_day'].replace(3,1,inplace=True)
# smoke_some_days
p['smoke_some_days'] = p['SMOKDAY2']
p['smoke_some_days'].replace(2,0,inplace=True)
# smoke_not_at_all
p['smoke_not_at_all'] = p['SMOKDAY2']
p['smoke_not_at_all'].replace(1,0,inplace=True)
p['smoke_not_at_all'].replace(2,1,inplace=True)
p = p.drop(['SMOKDAY2'], axis=1)

# USENOW3

In [119]:
# smokeless_every_day
p['smokeless_every_day'] = p['USENOW3']
p['smokeless_every_day'].replace(0,3,inplace=True)
p['smokeless_every_day'].replace([1,2],0,inplace=True)
p['smokeless_every_day'].replace(3,1,inplace=True)
# smoke_some_days
p['smokeless_some_days'] = p['USENOW3']
p['smokeless_some_days'].replace(2,0,inplace=True)
# smoke_not_at_all
p['smokeless_not_at_all'] = p['USENOW3']
p['smokeless_not_at_all'].replace(1,0,inplace=True)
p['smokeless_not_at_all'].replace(2,1,inplace=True)
p = p.drop(['USENOW3'], axis=1)

# ECIGNOW1

In [120]:
# smokeless_every_day
p['ecig_every_day'] = p['ECIGNOW1']
p['ecig_every_day'].replace(0,4,inplace=True)
p['ecig_every_day'].replace([1,2,3],0,inplace=True)
p['ecig_every_day'].replace(4,1,inplace=True)
# smoke_some_days
p['ecig_some_days'] = p['ECIGNOW1']
p['ecig_some_days'].replace([2,3],0,inplace=True)
# smoke_not_at_all
p['ecig_not_at_all'] = p['ECIGNOW1']
p['ecig_not_at_all'].replace([1,3],0,inplace=True)
p['ecig_not_at_all'].replace(2,1,inplace=True)
# ecig_never_used
p['ecig_never_used'] = p['ECIGNOW1']
p['ecig_never_used'].replace([1,2],0,inplace=True)
p['ecig_never_used'].replace(3,1,inplace=True)
p = p.drop(['ECIGNOW1'], axis=1)

# _IMPRACE

In [121]:
# white, non-hispanic
p['white'] = p['_IMPRACE']
p['white'].replace(0,6, inplace=True)
p['white'].replace([1,2,3,4,5],0, inplace=True)
p['white'].replace(6,1, inplace=True)
# black
p['black'] = p['_IMPRACE']
p['black'].replace([2,3,4,5],0, inplace=True)
# asian
p['asian'] = p['_IMPRACE']
p['asian'].replace([1,3,4,5],0, inplace=True)
p['asian'].replace(2,1, inplace=True)
# Native, non-hispanic
p['native'] = p['_IMPRACE']
p['native'].replace([1,2,4,5],0, inplace=True)
p['native'].replace(3,1, inplace=True)
# hispanic
p['hispanic'] = p['_IMPRACE']
p['hispanic'].replace([1,2,3,5],0, inplace=True)
p['hispanic'].replace(4,1, inplace=True)
# 'other' all coded to 0. no data loss
p = p.drop(['_IMPRACE'], axis=1)

# _EDUCAG

In [122]:
# Did not graduate High School
p['not_graduate_high_school'] = p['_EDUCAG']
p['not_graduate_high_school'].replace(0,4, inplace=True)
p['not_graduate_high_school'].replace([1,2,3],0, inplace=True)
p['not_graduate_high_school'].replace(4,1, inplace=True)
# graduated_high_school
p['graduated_high_school'] = p['_EDUCAG']
p['graduated_high_school'].replace([2,3],0, inplace=True)
# attended_college
p['attended_college'] = p['_EDUCAG']
p['attended_college'].replace([1,3],0, inplace=True)
p['attended_college'].replace(2,1, inplace=True)
# graduated_college
p['graduated_college'] = p['_EDUCAG']
p['graduated_college'].replace([1,2],0, inplace=True)
p['graduated_college'].replace(3,1, inplace=True)
p = p.drop(['_EDUCAG'], axis=1)

# FTJUDA2_

In [123]:
p.loc[p['FTJUDA2_2'] == 1, 'FTJUDA2_'] /= 7
p.loc[p['FTJUDA2_2'] == 2, 'FTJUDA2_'] /= 30
p.loc[p['FTJUDA2_2'] == 3, 'FTJUDA2_'] /= 365
p = p.drop(['FTJUDA2_2'], axis=1)

# FRUTDA2_

In [124]:
p.loc[p['FRUTDA2_2'] == 1, 'FRUTDA2_'] /= 7
p.loc[p['FRUTDA2_2'] == 2, 'FRUTDA2_'] /= 30
p.loc[p['FRUTDA2_2'] == 3, 'FRUTDA2_'] /= 365
p = p.drop(['FRUTDA2_2'], axis=1)

# GRENDA1_

In [125]:
p.loc[p['GRENDA1_2'] == 1, 'GRENDA1_'] /= 7
p.loc[p['GRENDA1_2'] == 2, 'GRENDA1_'] /= 30
p.loc[p['GRENDA1_2'] == 3, 'GRENDA1_'] /= 365
p = p.drop(['GRENDA1_2'], axis=1)

# FRNCHDA_

In [126]:
p.loc[p['FRNCHDA_2'] == 1, 'FRNCHDA_'] /= 7
p.loc[p['FRNCHDA_2'] == 2, 'FRNCHDA_'] /= 30
p.loc[p['FRNCHDA_2'] == 3, 'FRNCHDA_'] /= 365
p = p.drop(['FRNCHDA_2'], axis=1)

# POTADA1_

In [127]:
p.loc[p['POTADA1_2'] == 1, 'POTADA1_'] /= 7
p.loc[p['POTADA1_2'] == 2, 'POTADA1_'] /= 30
p.loc[p['POTADA1_2'] == 3, 'POTADA1_'] /= 365
p = p.drop(['POTADA1_2'], axis=1)

# VEGEDA2_

In [128]:
p.loc[p['VEGEDA2_2'] == 1, 'VEGEDA2_'] /= 7
p.loc[p['VEGEDA2_2'] == 2, 'VEGEDA2_'] /= 30
p.loc[p['VEGEDA2_2'] == 3, 'VEGEDA2_'] /= 365
p = p.drop(['VEGEDA2_2'], axis=1)

# ___ was missing

In [129]:
was_missing_columns=['PHYSHLTH_was_missing',
'MENTHLTH_was_missing',
'POORHLTH_was_missing',
'PERSDOC3_was_missing',
'MEDCOST1_was_missing',
'CHECKUP1_was_missing',
'EXERANY2_was_missing',
'BPMEDS_was_missing',
'TOLDHI3_was_missing',
'CHOLMED3_was_missing',
'CVDINFR4_was_missing',
'CVDCRHD4_was_missing',
'CVDSTRK3_was_missing',
'ASTHMA3_was_missing',
'ASTHNOW_was_missing',
'CHCSCNCR_was_missing',
'CHCOCNCR_was_missing',
'CHCCOPD3_was_missing',
'ADDEPEV3_was_missing',
'CHCKDNY2_was_missing',
'DIABETE4_was_missing',
'HAVARTH5_was_missing',
'VETERAN3_was_missing',
'PREGNANT_was_missing',
'DEAF_was_missing',
'BLIND_was_missing',
'DECIDE_was_missing',
'DIFFWALK_was_missing',
'DIFFDRES_was_missing',
'DIFFALON_was_missing',
'SMOKE100_was_missing',
'ALCDAY5_was_missing',
'AVEDRNK3_was_missing',
'DRNK3GE5_was_missing',
'MAXDRNKS_was_missing',
'FLUSHOT7_was_missing',
'PNEUVAC4_was_missing',
'HIVTST7_was_missing',
'_HLTHPLN_was_missing',
'HTIN4_was_missing',
'WTKG3_was_missing',
'_INCOMG1_was_missing',
'FTJUDA2__was_missing',
'FRUTDA2__was_missing',
'cholesterol_checked_within_year_was_missing',
'_METSTAT_and_URBSTAT_was_missing',
'BPHIGH6_was_missing',
'MARITAL_was_missing',
'RENTHOM1_was_missing',
'EMPLOY1_was_missing',
'SMOKDAY2_was_missing',
'USENOW3_was_missing',
'ECIGNOW1_was_missing',
'_EDUCAG_was_missing']
#was_missing_df = pd.DataFrame(0, index=np.arange(len(data)), columns=was_missing_columns)
was_missing_df = pd.DataFrame(0, index=[0],columns=was_missing_columns)

In [101]:
was_missing_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1 entries, 0 to 0
Data columns (total 54 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   PHYSHLTH_was_missing                         1 non-null      int64
 1   MENTHLTH_was_missing                         1 non-null      int64
 2   POORHLTH_was_missing                         1 non-null      int64
 3   PERSDOC3_was_missing                         1 non-null      int64
 4   MEDCOST1_was_missing                         1 non-null      int64
 5   CHECKUP1_was_missing                         1 non-null      int64
 6   EXERANY2_was_missing                         1 non-null      int64
 7   BPMEDS_was_missing                           1 non-null      int64
 8   TOLDHI3_was_missing                          1 non-null      int64
 9   CHOLMED3_was_missing                         1 non-null      int64
 10  CVDINFR4_was_missing                         1 non-null      int64
 11  CVDCRHD4_was_missing                         1 non-null      int64
 12  CVDSTRK3_was_missing                         1 non-null      int64
 13  ASTHMA3_was_missing                          1 non-null      int64
 14  ASTHNOW_was_missing                          1 non-null      int64
 15  CHCSCNCR_was_missing                         1 non-null      int64
 16  CHCOCNCR_was_missing                         1 non-null      int64
 17  CHCCOPD3_was_missing                         1 non-null      int64
 18  ADDEPEV3_was_missing                         1 non-null      int64
 19  CHCKDNY2_was_missing                         1 non-null      int64
 20  DIABETE4_was_missing                         1 non-null      int64
 21  HAVARTH5_was_missing                         1 non-null      int64
 22  VETERAN3_was_missing                         1 non-null      int64
 23  PREGNANT_was_missing                         1 non-null      int64
 24  DEAF_was_missing                             1 non-null      int64
 25  BLIND_was_missing                            1 non-null      int64
 26  DECIDE_was_missing                           1 non-null      int64
 27  DIFFWALK_was_missing                         1 non-null      int64
 28  DIFFDRES_was_missing                         1 non-null      int64
 29  DIFFALON_was_missing                         1 non-null      int64
 30  SMOKE100_was_missing                         1 non-null      int64
 31  ALCDAY5_was_missing                          1 non-null      int64
 32  AVEDRNK3_was_missing                         1 non-null      int64
 33  DRNK3GE5_was_missing                         1 non-null      int64
 34  MAXDRNKS_was_missing                         1 non-null      int64
 35  FLUSHOT7_was_missing                         1 non-null      int64
 36  PNEUVAC4_was_missing                         1 non-null      int64
 37  HIVTST7_was_missing                          1 non-null      int64
 38  _HLTHPLN_was_missing                         1 non-null      int64
 39  HTIN4_was_missing                            1 non-null      int64
 40  WTKG3_was_missing                            1 non-null      int64
 41  _INCOMG1_was_missing                         1 non-null      int64
 42  FTJUDA2__was_missing                         1 non-null      int64
 43  FRUTDA2__was_missing                         1 non-null      int64
 44  cholesterol_checked_within_year_was_missing  1 non-null      int64
 45  _METSTAT_and_URBSTAT_was_missing             1 non-null      int64
 46  BPHIGH6_was_missing                          1 non-null      int64
 47  MARITAL_was_missing                          1 non-null      int64
 48  RENTHOM1_was_missing                         1 non-null      int64
 49  EMPLOY1_was_missing                          1 non-null      int64
 50  SMOKDAY2_was_missing                         1 non-null      int64
 51  USENOW3_was_missing                          1 non-null      int64
 52  ECIGNOW1_was_missing                         1 non-null      int64
 53  _EDUCAG_was_missing                          1 non-null      int64
dtypes: int64(54)
memory usage: 440.0 bytes

In [130]:
final = pd.concat([p, was_missing_df], axis=1)

In [131]:
for i in range(0, len(df.columns)):
    print("["+str(i)+"]\tdf: "+df.columns[i]+"\tp: "+final.columns[i])

[0]	df: SEXVAR	p: SEXVAR
[1]	df: GENHLTH	p: GENHLTH
[2]	df: PHYSHLTH	p: PHYSHLTH
[3]	df: MENTHLTH	p: MENTHLTH
[4]	df: POORHLTH	p: POORHLTH
[5]	df: PERSDOC3	p: PERSDOC3
[6]	df: MEDCOST1	p: MEDCOST1
[7]	df: CHECKUP1	p: CHECKUP1
[8]	df: EXERANY2	p: EXERANY2
[9]	df: BPMEDS	p: BPMEDS
[10]	df: TOLDHI3	p: TOLDHI3
[11]	df: CHOLMED3	p: CHOLMED3
[12]	df: CVDINFR4	p: CVDINFR4
[13]	df: CVDCRHD4	p: CVDCRHD4
[14]	df: CVDSTRK3	p: CVDSTRK3
[15]	df: ASTHMA3	p: ASTHMA3
[16]	df: ASTHNOW	p: ASTHNOW
[17]	df: CHCSCNCR	p: CHCSCNCR
[18]	df: CHCOCNCR	p: CHCOCNCR
[19]	df: CHCCOPD3	p: CHCCOPD3
[20]	df: ADDEPEV3	p: ADDEPEV3
[21]	df: CHCKDNY2	p: CHCKDNY2
[22]	df: HAVARTH5	p: HAVARTH5
[23]	df: VETERAN3	p: VETERAN3
[24]	df: PREGNANT	p: PREGNANT
[25]	df: DEAF	p: DEAF
[26]	df: BLIND	p: BLIND
[27]	df: DECIDE	p: DECIDE
[28]	df: DIFFWALK	p: DIFFWALK
[29]	df: DIFFDRES	p: DIFFDRES
[30]	df: DIFFALON	p: DIFFALON
[31]	df: SMOKE100	p: SMOKE100
[32]	df: ALCDAY5	p: ALCDAY5
[33]	df: AVEDRNK3	p: AVEDRNK3
[34]	df: DRNK3GE5	p: DRNK3GE5
[35]	df: MAXDRNKS	p: MAXDRNKS
[36]	df: FLUSHOT7	p: FLUSHOT7
[37]	df: PNEUVAC4	p: PNEUVAC4
[38]	df: HIVTST7	p: HIVTST7
[39]	df: _METSTAT	p: _METSTAT
[40]	df: _URBSTAT	p: _URBSTAT
[41]	df: _HLTHPLN	p: _HLTHPLN
[42]	df: _AGE80	p: _AGE80
[43]	df: HTIN4	p: HTIN4
[44]	df: WTKG3	p: WTKG3
[45]	df: _INCOMG1	p: _INCOMG1
[46]	df: FTJUDA2_	p: FTJUDA2_
[47]	df: FRUTDA2_	p: FRUTDA2_
[48]	df: GRENDA1_	p: GRENDA1_
[49]	df: FRNCHDA_	p: FRNCHDA_
[50]	df: POTADA1_	p: POTADA1_
[51]	df: VEGEDA2_	p: VEGEDA2_
[52]	df: high_blood_pressure	p: high_blood_pressure
[53]	df: pregnant_high_blood_pressure	p: pregnant_high_blood_pressure
[54]	df: borderline_high_blood_pressure	p: borderline_high_blood_pressure
[55]	df: cholesterol_checked_within_year	p: cholesterol_checked_within_year
[56]	df: married	p: married
[57]	df: divorced	p: divorced
[58]	df: widowed	p: widowed
[59]	df: separated	p: separated
[60]	df: never_married	p: never_married
[61]	df: unmarried_couple	p: unmarried_couple
[62]	df: own_house	p: own_house
[63]	df: renting	p: renting
[64]	df: other_arrangement_housing	p: other_arrangement_housing
[65]	df: employed_for_wages	p: employed_for_wages
[66]	df: self_employed	p: self_employed
[67]	df: out_of_work_year_plus	p: out_of_work_year_plus
[68]	df: out_of_work_year_less	p: out_of_work_year_less
[69]	df: homemaker	p: homemaker
[70]	df: student	p: student
[71]	df: retired	p: retired
[72]	df: unable_to_work	p: unable_to_work
[73]	df: smoke_every_day	p: smoke_every_day
[74]	df: smoke_some_days	p: smoke_some_days
[75]	df: smoke_not_at_all	p: smoke_not_at_all
[76]	df: smokeless_every_day	p: smokeless_every_day
[77]	df: smokeless_some_days	p: smokeless_some_days
[78]	df: smokeless_not_at_all	p: smokeless_not_at_all
[79]	df: ecig_every_day	p: ecig_every_day
[80]	df: ecig_some_days	p: ecig_some_days
[81]	df: ecig_not_at_all	p: ecig_not_at_all
[82]	df: ecig_never_used	p: ecig_never_used
[83]	df: white	p: white
[84]	df: black	p: black
[85]	df: asian	p: asian
[86]	df: native	p: native
[87]	df: hispanic	p: hispanic
[88]	df: not_graduate_high_school	p: not_graduate_high_school
[89]	df: graduated_high_school	p: graduated_high_school
[90]	df: attended_college	p: attended_college
[91]	df: graduated_college	p: graduated_college
[92]	df: PHYSHLTH_was_missing	p: PHYSHLTH_was_missing
[93]	df: MENTHLTH_was_missing	p: MENTHLTH_was_missing
[94]	df: POORHLTH_was_missing	p: POORHLTH_was_missing
[95]	df: PERSDOC3_was_missing	p: PERSDOC3_was_missing
[96]	df: MEDCOST1_was_missing	p: MEDCOST1_was_missing
[97]	df: CHECKUP1_was_missing	p: CHECKUP1_was_missing
[98]	df: EXERANY2_was_missing	p: EXERANY2_was_missing
[99]	df: BPMEDS_was_missing	p: BPMEDS_was_missing
[100]	df: TOLDHI3_was_missing	p: TOLDHI3_was_missing
[101]	df: CHOLMED3_was_missing	p: CHOLMED3_was_missing
[102]	df: CVDINFR4_was_missing	p: CVDINFR4_was_missing
[103]	df: CVDCRHD4_was_missing	p: CVDCRHD4_was_missing
[104]	df: CVDSTRK3_was_missing	p: CVDSTRK3_was_missing
[105]	df: ASTHMA3_was_missing	p: ASTHMA3_was_missing
[106]	df: ASTHNOW_was_missing	p: ASTHNOW_was_missing
[107]	df: CHCSCNCR_was_missing	p: CHCSCNCR_was_missing
[108]	df: CHCOCNCR_was_missing	p: CHCOCNCR_was_missing
[109]	df: CHCCOPD3_was_missing	p: CHCCOPD3_was_missing
[110]	df: ADDEPEV3_was_missing	p: ADDEPEV3_was_missing
[111]	df: CHCKDNY2_was_missing	p: CHCKDNY2_was_missing
[112]	df: DIABETE4_was_missing	p: DIABETE4_was_missing
[113]	df: HAVARTH5_was_missing	p: HAVARTH5_was_missing
[114]	df: VETERAN3_was_missing	p: VETERAN3_was_missing
[115]	df: PREGNANT_was_missing	p: PREGNANT_was_missing
[116]	df: DEAF_was_missing	p: DEAF_was_missing
[117]	df: BLIND_was_missing	p: BLIND_was_missing
[118]	df: DECIDE_was_missing	p: DECIDE_was_missing
[119]	df: DIFFWALK_was_missing	p: DIFFWALK_was_missing
[120]	df: DIFFDRES_was_missing	p: DIFFDRES_was_missing
[121]	df: DIFFALON_was_missing	p: DIFFALON_was_missing
[122]	df: SMOKE100_was_missing	p: SMOKE100_was_missing
[123]	df: ALCDAY5_was_missing	p: ALCDAY5_was_missing
[124]	df: AVEDRNK3_was_missing	p: AVEDRNK3_was_missing
[125]	df: DRNK3GE5_was_missing	p: DRNK3GE5_was_missing
[126]	df: MAXDRNKS_was_missing	p: MAXDRNKS_was_missing
[127]	df: FLUSHOT7_was_missing	p: FLUSHOT7_was_missing
[128]	df: PNEUVAC4_was_missing	p: PNEUVAC4_was_missing
[129]	df: HIVTST7_was_missing	p: HIVTST7_was_missing
[130]	df: _HLTHPLN_was_missing	p: _HLTHPLN_was_missing
[131]	df: HTIN4_was_missing	p: HTIN4_was_missing
[132]	df: WTKG3_was_missing	p: WTKG3_was_missing
[133]	df: _INCOMG1_was_missing	p: _INCOMG1_was_missing
[134]	df: FTJUDA2__was_missing	p: FTJUDA2__was_missing
[135]	df: FRUTDA2__was_missing	p: FRUTDA2__was_missing
[136]	df: cholesterol_checked_within_year_was_missing	p: cholesterol_checked_within_year_was_missing
[137]	df: _METSTAT_and_URBSTAT_was_missing	p: _METSTAT_and_URBSTAT_was_missing
[138]	df: BPHIGH6_was_missing	p: BPHIGH6_was_missing
[139]	df: MARITAL_was_missing	p: MARITAL_was_missing
[140]	df: RENTHOM1_was_missing	p: RENTHOM1_was_missing
[141]	df: EMPLOY1_was_missing	p: EMPLOY1_was_missing
[142]	df: SMOKDAY2_was_missing	p: SMOKDAY2_was_missing
[143]	df: USENOW3_was_missing	p: USENOW3_was_missing
[144]	df: ECIGNOW1_was_missing	p: ECIGNOW1_was_missing
[145]	df: _EDUCAG_was_missing	p: _EDUCAG_was_missing

In [133]:
for i in range(0, len(final.columns)):
    if df.columns[i] != final.columns[i]:
        print("["+str(i)+"]\tdf: "+df.columns[i]+"\tp: "+final.columns[i])

In [109]:
p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 92 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   SEXVAR                           1 non-null      int64
 1   GENHLTH                          1 non-null      int64
 2   PHYSHLTH                         1 non-null      int64
 3   MENTHLTH                         1 non-null      int64
 4   POORHLTH                         1 non-null      int64
 5   PERSDOC3                         1 non-null      int64
 6   MEDCOST1                         1 non-null      int64
 7   CHECKUP1                         1 non-null      int64
 8   EXERANY2                         1 non-null      int64
 9   BPMEDS                           1 non-null      int64
 10  TOLDHI3                          1 non-null      int64
 11  CHOLMED3                         1 non-null      int64
 12  CVDINFR4                         1 non-null      int64
 13  CVDCRHD4                         1 non-null      int64
 14  CVDSTRK3                         1 non-null      int64
 15  ASTHMA3                          1 non-null      int64
 16  ASTHNOW                          1 non-null      int64
 17  CHCSCNCR                         1 non-null      int64
 18  CHCOCNCR                         1 non-null      int64
 19  CHCCOPD3                         1 non-null      int64
 20  ADDEPEV3                         1 non-null      int64
 21  CHCKDNY2                         1 non-null      int64
 22  HAVARTH5                         1 non-null      int64
 23  VETERAN3                         1 non-null      int64
 24  PREGNANT                         1 non-null      int64
 25  DEAF                             1 non-null      int64
 26  BLIND                            1 non-null      int64
 27  DECIDE                           1 non-null      int64
 28  DIFFWALK                         1 non-null      int64
 29  DIFFDRES                         1 non-null      int64
 30  DIFFALON                         1 non-null      int64
 31  SMOKE100                         1 non-null      int64
 32  ALCDAY5                          1 non-null      int64
 33  AVEDRNK3                         1 non-null      int64
 34  DRNK3GE5                         1 non-null      int64
 35  MAXDRNKS                         1 non-null      int64
 36  FLUSHOT7                         1 non-null      int64
 37  PNEUVAC4                         1 non-null      int64
 38  HIVTST7                          1 non-null      int64
 39  _METSTAT                         1 non-null      int64
 40  _URBSTAT                         1 non-null      int64
 41  _HLTHPLN                         1 non-null      int64
 42  _AGE80                           1 non-null      int64
 43  HTIN4                            1 non-null      int64
 44  WTKG3                            1 non-null      int64
 45  _INCOMG1                         1 non-null      int64
 46  FTJUDA2_                         1 non-null      int64
 47  FRUTDA2_                         1 non-null      int64
 48  GRENDA1_                         1 non-null      int64
 49  FRNCHDA_                         1 non-null      int64
 50  POTADA1_                         1 non-null      float64
 51  VEGEDA2_                         1 non-null      float64
 52  high_blood_pressure              1 non-null      int64
 53  pregnant_high_blood_pressure     1 non-null      int64
 54  borderline_high_blood_pressure   1 non-null      int64
 55  cholesterol_checked_within_year  1 non-null      int64
 56  married                          1 non-null      int64
 57  divorced                         1 non-null      int64
 58  widowed                          1 non-null      int64
 59  separated                        1 non-null      int64
 60  never_married                    1 non-null      int64
 61  unmarried_couple                 1 non-null      int64
 62  own_house                        1 non-null      int64
 63  renting                          1 non-null      int64
 64  other_arrangement_housing        1 non-null      int64
 65  employed_for_wages               1 non-null      int64
 66  self_employed                    1 non-null      int64
 67  out_of_work_year_plus            1 non-null      int64
 68  out_of_work_year_less            1 non-null      int64
 69  homemaker                        1 non-null      int64
 70  student                          1 non-null      int64
 71  retired                          1 non-null      int64
 72  unable_to_work                   1 non-null      int64
 73  smoke_every_day                  1 non-null      int64
 74  smoke_some_days                  1 non-null      int64
 75  smoke_not_at_all                 1 non-null      int64
 76  smokeless_every_day              1 non-null      int64
 77  smokeless_some_days              1 non-null      int64
 78  smokeless_not_at_all             1 non-null      int64
 79  ecig_every_day                   1 non-null      int64
 80  ecig_some_days                   1 non-null      int64
 81  ecig_not_at_all                  1 non-null      int64
 82  ecig_never_used                  1 non-null      int64
 83  white                            1 non-null      int64
 84  black                            1 non-null      int64
 85  asian                            1 non-null      int64
 86  native                           1 non-null      int64
 87  hispanic                         1 non-null      int64
 88  not_graduate_high_school         1 non-null      int64
 89  graduated_high_school            1 non-null      int64
 90  attended_college                 1 non-null      int64
 91  graduated_college                1 non-null      int64
dtypes: float64(2), int64(90)
memory usage: 864.0 bytes