In [1]:
import numpy as np
import pandas as pd

In [50]:
p = pd.read_csv('./input_test.csv')

In [51]:
p = p[p.columns[1:]]

In [52]:
p.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPHIGH6,...,FRUTDA2_,FRUTDA2_2,GRENDA1_,GRENDA1_2,FRNCHDA_,FRNCHDA_2,POTADA1_,POTADA1_2,VEGEDA2_,VEGEDA2_2
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,0.0,0.0,2.0,3.0,4.0,1.0,1.0,0.0,0.0,1.0,...,5.0,0.0,5.0,0.0,4.0,0.0,5.0,1.0,5.0,2.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.0,0.0,2.0,3.0,4.0,1.0,1.0,0.0,0.0,1.0,...,5.0,0.0,5.0,0.0,4.0,0.0,5.0,1.0,5.0,2.0
25%,0.0,0.0,2.0,3.0,4.0,1.0,1.0,0.0,0.0,1.0,...,5.0,0.0,5.0,0.0,4.0,0.0,5.0,1.0,5.0,2.0
50%,0.0,0.0,2.0,3.0,4.0,1.0,1.0,0.0,0.0,1.0,...,5.0,0.0,5.0,0.0,4.0,0.0,5.0,1.0,5.0,2.0
75%,0.0,0.0,2.0,3.0,4.0,1.0,1.0,0.0,0.0,1.0,...,5.0,0.0,5.0,0.0,4.0,0.0,5.0,1.0,5.0,2.0
max,0.0,0.0,2.0,3.0,4.0,1.0,1.0,0.0,0.0,1.0,...,5.0,0.0,5.0,0.0,4.0,0.0,5.0,1.0,5.0,2.0

In [45]:
#df = pd.read_csv('../data/brfss_imputed.csv')
df = pd.read_csv('./X_test.csv')

In [46]:
df = df[df.columns[1:]]

In [47]:
df.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPMEDS,...,cholesterol_checked_within_year_was_missing,_METSTAT_and_URBSTAT_was_missing,BPHIGH6_was_missing,MARITAL_was_missing,RENTHOM1_was_missing,EMPLOY1_was_missing,SMOKDAY2_was_missing,USENOW3_was_missing,ECIGNOW1_was_missing,_EDUCAG_was_missing
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,1.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [75]:
for i in range(0, len(df.columns)):
    print("["+str(i)+"]\tdf: "+df.columns[i]+"\tp: "+p.columns[i])

[0]	df: SEXVAR	p: SEXVAR
[1]	df: GENHLTH	p: GENHLTH
[2]	df: PHYSHLTH	p: PHYSHLTH
[3]	df: MENTHLTH	p: MENTHLTH
[4]	df: POORHLTH	p: POORHLTH
[5]	df: PERSDOC3	p: PERSDOC3
[6]	df: MEDCOST1	p: MEDCOST1
[7]	df: CHECKUP1	p: CHECKUP1
[8]	df: EXERANY2	p: EXERANY2
[9]	df: BPMEDS	p: BPMEDS
[10]	df: TOLDHI3	p: TOLDHI3
[11]	df: CHOLMED3	p: CHOLMED3
[12]	df: CVDINFR4	p: CVDINFR4
[13]	df: CVDCRHD4	p: CVDCRHD4
[14]	df: CVDSTRK3	p: CVDSTRK3
[15]	df: ASTHMA3	p: ASTHMA3
[16]	df: ASTHNOW	p: ASTHNOW
[17]	df: CHCSCNCR	p: CHCSCNCR
[18]	df: CHCOCNCR	p: CHCOCNCR
[19]	df: CHCCOPD3	p: CHCCOPD3
[20]	df: ADDEPEV3	p: ADDEPEV3
[21]	df: CHCKDNY2	p: CHCKDNY2
[22]	df: HAVARTH5	p: HAVARTH5
[23]	df: VETERAN3	p: VETERAN3
[24]	df: PREGNANT	p: PREGNANT
[25]	df: DEAF	p: DEAF
[26]	df: BLIND	p: BLIND
[27]	df: DECIDE	p: DECIDE
[28]	df: DIFFWALK	p: DIFFWALK
[29]	df: DIFFDRES	p: DIFFDRES
[30]	df: DIFFALON	p: DIFFALON
[31]	df: SMOKE100	p: SMOKE100
[32]	df: ALCDAY5	p: ALCDAY5
[33]	df: AVEDRNK3	p: AVEDRNK3
[34]	df: DRNK3GE5	p: DRNK3GE5
[35]	df: MAXDRNKS	p: MAXDRNKS
[36]	df: FLUSHOT7	p: FLUSHOT7
[37]	df: PNEUVAC4	p: PNEUVAC4
[38]	df: HIVTST7	p: HIVTST7
[39]	df: _METSTAT	p: _METSTAT
[40]	df: _URBSTAT	p: _URBSTAT
[41]	df: _HLTHPLN	p: _HLTHPLN
[42]	df: _AGE80	p: _AGE80
[43]	df: HTIN4	p: HTIN4
[44]	df: WTKG3	p: WTKG3
[45]	df: _INCOMG1	p: _EDUCAG
[46]	df: FTJUDA2_	p: _INCOMG1
[47]	df: FRUTDA2_	p: FTJUDA2_
[48]	df: GRENDA1_	p: FTJUDA2_2
[49]	df: FRNCHDA_	p: FRUTDA2_
[50]	df: POTADA1_	p: FRUTDA2_2
[51]	df: VEGEDA2_	p: GRENDA1_
[52]	df: high_blood_pressure	p: GRENDA1_2
[53]	df: pregnant_high_blood_pressure	p: FRNCHDA_
[54]	df: borderline_high_blood_pressure	p: FRNCHDA_2
[55]	df: cholesterol_checked_within_year	p: POTADA1_
[56]	df: married	p: POTADA1_2
[57]	df: divorced	p: VEGEDA2_
[58]	df: widowed	p: VEGEDA2_2
[59]	df: separated	p: high_blood_pressure
[60]	df: never_married	p: pregnant_high_blood_pressure
[61]	df: unmarried_couple	p: borderline_high_blood_pressure
[62]	df: own_house	p: cholesterol_checked_within_year
[63]	df: renting	p: married
[64]	df: other_arrangement_housing	p: divorced
[65]	df: employed_for_wages	p: widowed
[66]	df: self_employed	p: separated
[67]	df: out_of_work_year_plus	p: never_married
[68]	df: out_of_work_year_less	p: unmarried_couple
[69]	df: homemaker	p: own_house
[70]	df: student	p: renting
[71]	df: retired	p: other_arrangement_housing
[72]	df: unable_to_work	p: employed_for_wages
[73]	df: smoke_every_day	p: self_employed
[74]	df: smoke_some_days	p: out_of_work_year_plus
[75]	df: smoke_not_at_all	p: out_of_work_year_less
[76]	df: smokeless_every_day	p: homemaker
[77]	df: smokeless_some_days	p: student
[78]	df: smokeless_not_at_all	p: retired
[79]	df: ecig_every_day	p: unable_to_work
[80]	df: ecig_some_days	p: smoke_every_day
[81]	df: ecig_not_at_all	p: smoke_some_days
[82]	df: ecig_never_used	p: smoke_not_at_all
[83]	df: white	p: smokeless_every_day
[84]	df: black	p: smokeless_some_days
[85]	df: asian	p: smokeless_not_at_all
[86]	df: native	p: ecig_every_day
[87]	df: hispanic	p: ecig_some_days
[88]	df: not_graduate_high_school	p: ecig_not_at_all
[89]	df: graduated_high_school	p: ecig_never_used
[90]	df: attended_college	p: white
[91]	df: graduated_college	p: black
[92]	df: PHYSHLTH_was_missing	p: asian
[93]	df: MENTHLTH_was_missing	p: native
[94]	df: POORHLTH_was_missing	p: hispanic

IndexError: index 95 is out of bounds for axis 0 with size 95

In [74]:
for i in range(0, len(df.columns)):
    if df.columns[i] != p.columns[i]:
        print("["+str(i)+"]\tdf: "+df.columns[i]+"\tp: "+p.columns[i])

[45]	df: _INCOMG1	p: _EDUCAG
[46]	df: FTJUDA2_	p: _INCOMG1
[47]	df: FRUTDA2_	p: FTJUDA2_
[48]	df: GRENDA1_	p: FTJUDA2_2
[49]	df: FRNCHDA_	p: FRUTDA2_
[50]	df: POTADA1_	p: FRUTDA2_2
[51]	df: VEGEDA2_	p: GRENDA1_
[52]	df: high_blood_pressure	p: GRENDA1_2
[53]	df: pregnant_high_blood_pressure	p: FRNCHDA_
[54]	df: borderline_high_blood_pressure	p: FRNCHDA_2
[55]	df: cholesterol_checked_within_year	p: POTADA1_
[56]	df: married	p: POTADA1_2
[57]	df: divorced	p: VEGEDA2_
[58]	df: widowed	p: VEGEDA2_2
[59]	df: separated	p: high_blood_pressure
[60]	df: never_married	p: pregnant_high_blood_pressure
[61]	df: unmarried_couple	p: borderline_high_blood_pressure
[62]	df: own_house	p: cholesterol_checked_within_year
[63]	df: renting	p: married
[64]	df: other_arrangement_housing	p: divorced
[65]	df: employed_for_wages	p: widowed
[66]	df: self_employed	p: separated
[67]	df: out_of_work_year_plus	p: never_married
[68]	df: out_of_work_year_less	p: unmarried_couple
[69]	df: homemaker	p: own_house
[70]	df: student	p: renting
[71]	df: retired	p: other_arrangement_housing
[72]	df: unable_to_work	p: employed_for_wages
[73]	df: smoke_every_day	p: self_employed
[74]	df: smoke_some_days	p: out_of_work_year_plus
[75]	df: smoke_not_at_all	p: out_of_work_year_less
[76]	df: smokeless_every_day	p: homemaker
[77]	df: smokeless_some_days	p: student
[78]	df: smokeless_not_at_all	p: retired
[79]	df: ecig_every_day	p: unable_to_work
[80]	df: ecig_some_days	p: smoke_every_day
[81]	df: ecig_not_at_all	p: smoke_some_days
[82]	df: ecig_never_used	p: smoke_not_at_all
[83]	df: white	p: smokeless_every_day
[84]	df: black	p: smokeless_some_days
[85]	df: asian	p: smokeless_not_at_all
[86]	df: native	p: ecig_every_day
[87]	df: hispanic	p: ecig_some_days
[88]	df: not_graduate_high_school	p: ecig_not_at_all
[89]	df: graduated_high_school	p: ecig_never_used
[90]	df: attended_college	p: white
[91]	df: graduated_college	p: black
[92]	df: PHYSHLTH_was_missing	p: asian
[93]	df: MENTHLTH_was_missing	p: native
[94]	df: POORHLTH_was_missing	p: hispanic

IndexError: index 95 is out of bounds for axis 0 with size 95

# BPHIGH6

In [55]:
p['high_blood_pressure'] = p['BPHIGH6']
p['high_blood_pressure'].replace([0,1,2],0, inplace=True)
p['high_blood_pressure'].replace(3,1, inplace=True)
p['pregnant_high_blood_pressure'] = p['BPHIGH6']
p['pregnant_high_blood_pressure'].replace([0,1,3],0, inplace=True)
p['pregnant_high_blood_pressure'].replace(2,1, inplace=True)
p['borderline_high_blood_pressure'] = p['BPHIGH6']
p['borderline_high_blood_pressure'].replace([0,2,3],0, inplace=True)
p = p.drop(['BPHIGH6'], axis=1)

# CHOLCHK3

In [56]:
# cholesterol checked within last year
p['cholesterol_checked_within_year'] = p['CHOLCHK3']
p = p.drop(['CHOLCHK3'], axis=1)

# MARITAL

In [57]:
# married
p['married'] = p['MARITAL']
p['married'].replace([1,2,3,4,5],2, inplace=True)
p['married'].replace(0,1, inplace=True)
p['married'].replace(2,0, inplace=True)
# divorced
p['divorced'] = p['MARITAL']
p['divorced'].replace([0,2,3,4,5],0, inplace=True)
# widowed
p['widowed'] = p['MARITAL']
p['widowed'].replace([1,3,4,5],0, inplace=True)
p['widowed'].replace(2,1, inplace=True)
# separated
p['separated'] = p['MARITAL']
p['separated'].replace([1,2,4,5],0, inplace=True)
p['separated'].replace(3,1, inplace=True)
# never_married
p['never_married'] = p['MARITAL']
p['never_married'].replace([1,2,3,5],0, inplace=True)
p['never_married'].replace(4,1, inplace=True)
# unmarried_couple
p['unmarried_couple'] = p['MARITAL']
p['unmarried_couple'].replace([1,2,3,4],0, inplace=True)
p['unmarried_couple'].replace(5,1, inplace=True)
p = p.drop(['MARITAL'], axis=1)

# RENTHOM1

In [58]:
# own
p['own_house'] = p['RENTHOM1']
p['own_house'].replace([1,2],2, inplace=True)
p['own_house'].replace(0,1, inplace=True)
p['own_house'].replace(2,0, inplace=True)
# renting
p['renting'] = p['RENTHOM1']
p['renting'].replace([0,2],0, inplace=True)
# other_arrangement_housing
p['other_arrangement_housing'] = p['RENTHOM1']
p['other_arrangement_housing'].replace([0,1],0, inplace=True)
p['other_arrangement_housing'].replace(2,1, inplace=True)
p = p.drop(['RENTHOM1'], axis=1)

# EMPLOY1

In [61]:
# employed for wages
p['employed_for_wages'] = p['EMPLOY1']
p['employed_for_wages'].replace(0,10, inplace=True)
p['employed_for_wages'].replace([1,2,3,4,5,6,7],0, inplace=True)
p['employed_for_wages'].replace(10,1, inplace=True)
# self_employed
p['self_employed'] = p['EMPLOY1']
p['self_employed'].replace([2,3,4,5,6,7],0, inplace=True)
# out_of_work_year_plus
p['out_of_work_year_plus'] = p['EMPLOY1']
p['out_of_work_year_plus'].replace([1,3,4,5,6,7],0, inplace=True)
p['out_of_work_year_plus'].replace(2,1, inplace=True)
# out_of_work_year_less
p['out_of_work_year_less'] = p['EMPLOY1']
p['out_of_work_year_less'].replace([1,2,4,5,6,7],0, inplace=True)
p['out_of_work_year_less'].replace(3,1, inplace=True)
# homemaker
p['homemaker'] = p['EMPLOY1']
p['homemaker'].replace([1,2,3,5,6,7],0, inplace=True)
p['homemaker'].replace(4,1, inplace=True)
# student
p['student'] = p['EMPLOY1']
p['student'].replace([1,2,3,4,6,7],0, inplace=True)
p['student'].replace(5,1, inplace=True)
# retired
p['retired'] = p['EMPLOY1']
p['retired'].replace([1,2,3,4,5,7],0, inplace=True)
p['retired'].replace(6,1, inplace=True)
# unable_to_work
p['unable_to_work'] = p['EMPLOY1']
p['unable_to_work'].replace([1,2,3,4,5,6],0, inplace=True)
p['unable_to_work'].replace(7,1, inplace=True)
p = p.drop(['EMPLOY1'], axis=1)

# SMOKDAY2

In [64]:
# smoke every day
p['smoke_every_day'] = p['SMOKDAY2']
p['smoke_every_day'].replace(0,3,inplace=True)
p['smoke_every_day'].replace([1,2],0,inplace=True)
p['smoke_every_day'].replace(3,1,inplace=True)
# smoke_some_days
p['smoke_some_days'] = p['SMOKDAY2']
p['smoke_some_days'].replace(2,0,inplace=True)
# smoke_not_at_all
p['smoke_not_at_all'] = p['SMOKDAY2']
p['smoke_not_at_all'].replace(1,0,inplace=True)
p['smoke_not_at_all'].replace(2,1,inplace=True)
p = p.drop(['SMOKDAY2'], axis=1)

# USENOW3

In [68]:
# smokeless_every_day
p['smokeless_every_day'] = p['USENOW3']
p['smokeless_every_day'].replace(0,3,inplace=True)
p['smokeless_every_day'].replace([1,2],0,inplace=True)
p['smokeless_every_day'].replace(3,1,inplace=True)
# smoke_some_days
p['smokeless_some_days'] = p['USENOW3']
p['smokeless_some_days'].replace(2,0,inplace=True)
# smoke_not_at_all
p['smokeless_not_at_all'] = p['USENOW3']
p['smokeless_not_at_all'].replace(1,0,inplace=True)
p['smokeless_not_at_all'].replace(2,1,inplace=True)
p = p.drop(['USENOW3'], axis=1)

# ECIGNOW1

In [70]:
# smokeless_every_day
p['ecig_every_day'] = p['ECIGNOW1']
p['ecig_every_day'].replace(0,4,inplace=True)
p['ecig_every_day'].replace([1,2,3],0,inplace=True)
p['ecig_every_day'].replace(4,1,inplace=True)
# smoke_some_days
p['ecig_some_days'] = p['ECIGNOW1']
p['ecig_some_days'].replace([2,3],0,inplace=True)
# smoke_not_at_all
p['ecig_not_at_all'] = p['ECIGNOW1']
p['ecig_not_at_all'].replace([1,3],0,inplace=True)
p['ecig_not_at_all'].replace(2,1,inplace=True)
# ecig_never_used
p['ecig_never_used'] = p['ECIGNOW1']
p['ecig_never_used'].replace([1,2],0,inplace=True)
p['ecig_never_used'].replace(3,1,inplace=True)
p = p.drop(['ECIGNOW1'], axis=1)

# _IMPRACE

In [73]:
# white, non-hispanic
p['white'] = p['_IMPRACE']
p['white'].replace(0,6, inplace=True)
p['white'].replace([1,2,3,4,5],0, inplace=True)
p['white'].replace(6,1, inplace=True)
# black
p['black'] = p['_IMPRACE']
p['black'].replace([2,3,4,5],0, inplace=True)
# asian
p['asian'] = p['_IMPRACE']
p['asian'].replace([1,3,4,5],0, inplace=True)
p['asian'].replace(2,1, inplace=True)
# Native, non-hispanic
p['native'] = p['_IMPRACE']
p['native'].replace([1,2,4,5],0, inplace=True)
p['native'].replace(3,1, inplace=True)
# hispanic
p['hispanic'] = p['_IMPRACE']
p['hispanic'].replace([1,2,3,5],0, inplace=True)
p['hispanic'].replace(4,1, inplace=True)
# 'other' all coded to 0. no data loss
p = p.drop(['_IMPRACE'], axis=1)