In [1]:
import numpy as np
import pandas as pd

In [7]:
p = pd.read_csv('./input_test.csv')

In [8]:
p = p[p.columns[1:]]

In [9]:
p.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPHIGH6,...,FRUTDA2_,FRUTDA2_2,GRENDA1_,GRENDA1_2,FRNCHDA_,FRNCHDA_2,POTADA1_,POTADA1_2,VEGEDA2_,VEGEDA2_2
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df = pd.read_csv('../data/brfss_imputed.csv')

In [12]:
df = df[df.columns[1:]]

In [13]:
df.describe()

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPMEDS,...,cholesterol_checked_within_year_was_missing,_METSTAT_and_URBSTAT_was_missing,BPHIGH6_was_missing,MARITAL_was_missing,RENTHOM1_was_missing,EMPLOY1_was_missing,SMOKDAY2_was_missing,USENOW3_was_missing,ECIGNOW1_was_missing,_EDUCAG_was_missing
count,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,...,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000,377880.000000
mean,0.538470,1.502662,3.783661,4.120906,2.758177,0.883024,0.073253,0.777720,0.763602,0.325876,...,0.061133,0.016900,0.003345,0.008468,0.007640,0.007391,0.000696,0.001088,0.001342,0.003562
std,0.498519,1.043368,8.312136,8.131098,7.034716,0.321392,0.260552,0.415779,0.424870,0.468702,...,0.239575,0.128895,0.057739,0.091633,0.087073,0.085654,0.026372,0.032962,0.036605,0.059576
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,2.000000,2.000000,4.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,4.000000,30.000000,30.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [20]:
for i in range(0, len(df.columns)):
    print("df: "+df.columns[i]+"\tp: "+p.columns[i])

df: SEXVAR	p: SEXVAR
df: GENHLTH	p: GENHLTH
df: PHYSHLTH	p: PHYSHLTH
df: MENTHLTH	p: MENTHLTH
df: POORHLTH	p: POORHLTH
df: PERSDOC3	p: PERSDOC3
df: MEDCOST1	p: MEDCOST1
df: CHECKUP1	p: CHECKUP1
df: EXERANY2	p: EXERANY2
df: BPMEDS	p: BPHIGH6
df: TOLDHI3	p: BPMEDS
df: CHOLMED3	p: cholesterol_checked_within_year
df: CVDINFR4	p: TOLDHI3
df: CVDCRHD4	p: CHOLMED3
df: CVDSTRK3	p: MARITAL
df: ASTHMA3	p: RENTHOM1
df: ASTHNOW	p: VETERAN3
df: CHCSCNCR	p: EMPLOY1
df: CHCOCNCR	p: PREGNANT
df: CHCCOPD3	p: DEAF
df: ADDEPEV3	p: BLIND
df: CHCKDNY2	p: DECIDE
df: DIABETE4	p: DIFFWALK
df: HAVARTH5	p: DIFFDRES
df: VETERAN3	p: DIFFALON
df: PREGNANT	p: SMOKE100
df: DEAF	p: SMOKDAY2
df: BLIND	p: USENOW3
df: DECIDE	p: ECIGNOW1
df: DIFFWALK	p: ALCDAY5
df: DIFFDRES	p: AVEDRNK3
df: DIFFALON	p: DRNK3GE5
df: SMOKE100	p: MAXDRNKS
df: ALCDAY5	p: FLUSHOT7
df: AVEDRNK3	p: PNEUVAC4
df: DRNK3GE5	p: HIVTST7
df: MAXDRNKS	p: _METSTAT
df: FLUSHOT7	p: _URBSTAT
df: PNEUVAC4	p: _IMPRACE
df: HIVTST7	p: _HLTHPLN
df: _METSTAT	p: _AGE80
df: _URBSTAT	p: HTIN4
df: _HLTHPLN	p: WTKG3
df: _AGE80	p: _EDUCAG
df: HTIN4	p: _INCOMG1
df: WTKG3	p: FTJUDA2_
df: _INCOMG1	p: FTJUDA2_2
df: FTJUDA2_	p: FRUTDA2_
df: FRUTDA2_	p: FRUTDA2_2
df: GRENDA1_	p: GRENDA1_
df: FRNCHDA_	p: GRENDA1_2
df: POTADA1_	p: FRNCHDA_
df: VEGEDA2_	p: FRNCHDA_2
df: high_blood_pressure	p: POTADA1_
df: pregnant_high_blood_pressure	p: POTADA1_2
df: borderline_high_blood_pressure	p: VEGEDA2_
df: cholesterol_checked_within_year	p: VEGEDA2_2

IndexError: index 57 is out of bounds for axis 0 with size 57